import {r,type SubjectConfig,type Topic} from "./subjectTypes";
const t=(title:string,intro:string,resources:ReturnType<typeof r>[]):Topic=>({title,intro,resources});
const base=["开始之前",[["intro","本站目的"],["how","如何使用本站"],["plan","学习规划"]]] as const;
const topics:Record<string,Topic>={
 tools:t("学习工具","检索序列、蛋白结构和论文，并记录可复现的观察与分析。",[]),
 foundations:t("化学与生命基础","先理解原子、化学键、能量、水和大分子，再进入细胞。",[r("OpenStax Concepts of Biology","https://openstax.org/details/books/concepts-biology","入门","开放教材","无需前置","用较少数学建立生命科学全景。"),r("MIT 7.01SC Fundamentals of Biology","https://ocw.mit.edu/courses/7-01sc-fundamentals-of-biology-fall-2011/","进阶","公开课","高中化学","专为自学组织的视频、讲义和习题。"),r("MIT 5.111SC Principles of Chemical Science","https://ocw.mit.edu/courses/5-111sc-principles-of-chemical-science-fall-2014/","高级","公开课","高中代数与化学","从化学结构和热力学补强生命科学基础。")]),
 cell:t("细胞生物学","理解膜、细胞器、能量转换、信号和细胞周期。",[r("OpenStax Biology 2e: The Cell","https://openstax.org/books/biology-2e/pages/4-introduction","入门","开放教材","基础化学","图文介绍细胞结构、膜与代谢。"),r("MIT 7.06x Cell Biology","https://ocw.mit.edu/courses/res-7-007-7-06x-cell-biology/","进阶","公开课","普通生物与化学","从实验角度研究膜运输、细胞骨架和信号。"),r("Molecular Biology of the Cell","https://www.ncbi.nlm.nih.gov/books/NBK21054/","高级","开放教材","细胞与分子生物学","NCBI 免费收录的经典教材版本。")]),
 genetics:t("遗传学","从孟德尔规律进入基因组、重组、群体遗传和复杂性状。",[r("OpenStax Biology 2e: Genetics","https://openstax.org/books/biology-2e/pages/12-introduction","入门","开放教材","细胞分裂","从遗传规律、染色体到现代遗传学。"),r("MIT 7.03x Genetics","https://ocw.mit.edu/courses/res-7-006-7-03x-genetics/","进阶","公开课","普通生物与概率基础","通过遗传分析连接基因、表型和分子机制。"),r("OpenStax Population Genetics","https://openstax.org/books/biology-2e/pages/19-2-population-genetics","高级","开放教材","遗传学、概率与微积分","进入等位基因频率、漂变、选择和数量模型。")]),
 evolution:t("演化与生态","用共同祖先、自然选择和生态系统解释生命多样性。",[r("OpenStax Biology 2e: Evolution","https://openstax.org/books/biology-2e/pages/18-introduction","入门","开放教材","遗传学基础","建立演化证据、机制和物种形成框架。"),r("MIT 7.014 Introductory Biology","https://ocw.mit.edu/courses/7-014-introductory-biology-spring-2005/","进阶","公开课","普通生物","把分子、遗传、演化和生态连成整体。"),r("MIT Evolutionary Biology","https://ocw.mit.edu/search/?q=evolutionary%20biology","高级","公开课","遗传学、生态与统计","继续学习群体遗传、系统发育和演化动力学。")]),
 molecular:t("生物化学与分子生物学","理解蛋白质、酶、DNA、RNA 和基因表达。",[r("OpenStax Biology 2e: Molecular Biology","https://openstax.org/books/biology-2e/pages/14-introduction","入门","开放教材","细胞与基础化学","清晰介绍 DNA、复制、转录和翻译。"),r("MIT 7.05 General Biochemistry","https://ocw.mit.edu/courses/7-05-general-biochemistry-spring-2020/","进阶","公开课","有机化学与普通生物","系统学习蛋白质、代谢与生物能量。"),r("MIT 7.28x Molecular Biology","https://ocw.mit.edu/courses/res-7-008-7-28x-molecular-biology/","高级","公开课","遗传、生化与细胞生物学","以实验推理深入 DNA 复制、修复和表达调控。")]),
 physiology:t("生理学与神经科学","理解器官系统如何维持稳态并协调行为。",[r("OpenStax Anatomy and Physiology 2e","https://openstax.org/details/books/anatomy-and-physiology-2e","入门","开放教材","细胞生物学","开放教材，覆盖人体结构与主要生理系统。"),r("MIT Human Physiology","https://ocw.mit.edu/search/?q=human%20physiology","进阶","公开课","细胞、生化与基础物理","从大学课程继续学习神经、循环和内分泌。"),r("Neuroscience — NCBI Bookshelf","https://www.ncbi.nlm.nih.gov/books/NBK10799/","高级","开放教材","生理学与细胞信号","免费经典教材，深入神经系统结构与功能。")]),
 bioinformatics:t("生物信息学","用计算和统计分析序列、基因组与分子数据。",[r("Rosalind","https://rosalind.info/","入门","项目平台","基础 Python","通过渐进题目学习序列处理和算法。"),r("MIT Computational Biology","https://ocw.mit.edu/search/?q=computational%20biology","进阶","公开课","编程、概率与分子生物学","学习比对、组装、基因组和网络分析。"),r("NCBI BLAST Documentation","https://blast.ncbi.nlm.nih.gov/doc/blast-help/","高级","公开讲义","序列分析与统计","理解数据库搜索参数、显著性和结果边界。")]),
 projects:t("项目与进阶方向","用观察、公开数据或计算实验提出并检验生物问题。",[r("iNaturalist","https://www.inaturalist.org/","入门","项目平台","无需前置","记录物种观察并参与公民科学。"),r("NCBI Datasets","https://www.ncbi.nlm.nih.gov/datasets/","进阶","项目平台","遗传学、统计与编程","下载基因组数据完成可复现分析。"),r("Protein Data Bank","https://www.rcsb.org/","高级","项目平台","生化、结构生物学与编程","使用真实结构数据研究蛋白功能与相互作用。")]),
 books:t("书单与资源","集中查看开放教材和大学公开课程。",[])
};
export const biology:SubjectConfig={slug:"biology",name:"生物",en:"BIOLOGY",intro:"生物学从分子、细胞和遗传机制出发，解释个体、种群与生态系统如何运作和演化。",caution:"生物事实很多，但主线是机制和证据。学习时持续追问：现象如何被测量，结论由什么实验支持，还有哪些替代解释？",groups:[base,["基础",[["tools","学习工具"],["foundations","化学与生命基础"],["cell","细胞生物学"]]],["核心",[["genetics","遗传学"],["evolution","演化与生态"],["molecular","生物化学与分子生物学"],["physiology","生理学与神经科学"]]],["研究与实践",[["bioinformatics","生物信息学"],["projects","项目与进阶方向"],["books","书单与资源"]]]],topics,phases:[{time:"1–2 个月",title:"建立生命与化学语言",goal:"看懂细胞和分子层面的基本过程。",learn:"化学键、水、大分子、能量、细胞结构。",done:"能画图解释膜、酶和能量转换。",link:"foundations"},{time:"3–5 个月",title:"掌握细胞、遗传与分子机制",goal:"理解信息如何保存、表达和传递。",learn:"细胞周期、DNA、RNA、蛋白质、代谢与信号。",done:"能从实验结果推断遗传或分子机制。",link:"molecular"},{time:"2–4 个月",title:"连接演化、生态与生理",goal:"跨尺度解释生命现象。",learn:"自然选择、种群、生态关系、稳态和器官系统。",done:"能区分近因机制与演化解释。",link:"evolution"},{time:"2–4 个月",title:"学习定量与计算方法",goal:"用数据而非印象支持结论。",learn:"实验设计、统计、序列分析和数据库检索。",done:"完成一个带代码或分析记录的数据项目。",link:"bioinformatics"},{time:"持续",title:"进入研究问题",goal:"阅读原始研究并形成可检验问题。",learn:"论文拆解、复现、开放数据和科学写作。",done:"提交一份包含方法、结果、限制和引用的报告。",link:"projects"}],tools:[["文献与知识",[["PubMed","https://pubmed.ncbi.nlm.nih.gov/","检索生命与医学文献"],["Zotero","https://www.zotero.org/","管理论文和引用"],["NCBI Bookshelf","https://www.ncbi.nlm.nih.gov/books/","查找免费生物医学教材"]]],["数据与分子",[["NCBI","https://www.ncbi.nlm.nih.gov/","基因、基因组和文献数据库"],["UniProt","https://www.uniprot.org/","检索蛋白序列与功能"],["RCSB PDB","https://www.rcsb.org/","查看蛋白质三维结构"],["BLAST","https://blast.ncbi.nlm.nih.gov/Blast.cgi","比较生物序列"]]],["分析与观察",[["Python","https://www.python.org/","处理序列和实验数据"],["R","https://www.r-project.org/","统计分析与可视化"],["iNaturalist","https://www.inaturalist.org/","物种观察和公民科学"]]]],books:[["OpenStax Biology 2e","https://openstax.org/details/books/biology-2e","普通生物 · 入门","完整开放教材，适合主线学习。"],["Molecular Biology of the Cell","https://www.ncbi.nlm.nih.gov/books/NBK21054/","细胞 · 进阶","NCBI 免费提供的经典教材版本。"],["Neuroscience","https://www.ncbi.nlm.nih.gov/books/NBK10799/","神经科学 · 进阶","系统理解神经系统。"]],portals:[["MIT","MIT OCW Biology","https://ocw.mit.edu/search/?d=Biology","从普通生物到分子、遗传和神经科学。"],["OpenStax","OpenStax Science","https://openstax.org/subjects/science","合法免费阅读的生物与解剖教材。"],["NCBI","NCBI Bookshelf","https://www.ncbi.nlm.nih.gov/books/","生物医学教材与专题资料库。"]]};
