export const groups=[
 ["开始之前",[["intro","本站目的"],["how","如何使用本站"],["plan","学习规划"]]],
 ["基础工具",[["tools","学习工具"],["accounting","会计基础"],["math","数学与统计"]]],
 ["经济学基础",[["micro","微观经济学"],["macro","宏观经济学"],["econometrics","计量经济学"]]],
 ["金融学核心",[["corporate","公司金融"],["investments","投资学"],["pricing","资产定价"],["fixed-income","固定收益"]]],
 ["进阶研究与实践",[["valuation","企业研究与估值"],["empirical","实证金融"],["macro-research","宏观与政策研究"],["risk","风险管理"],["behavioral","行为金融"],["quant","量化研究"],["projects","研究方法与项目"],["books","书单与资源"]]]
] as const;
type Res={name:string,url:string,level:string,kind?:string,pre?:string};
const R=(name:string,url:string,level:string,kind="公开课",pre="具备上一阶段的基础知识"):Res=>({name,url,level,kind,pre});
export const topics:Record<string,{title:string,intro:string;resources:Res[]}>= {
 tools:{title:"学习工具",intro:"用稳定的工作流整理资料、处理数据并复现研究。",resources:[R("Obsidian","https://obsidian.md/","入门","工具","无需前置"),R("Zotero","https://www.zotero.org/","入门","工具","无需前置"),R("Python","https://www.python.org/","进阶","工具","基础编程")]},
 accounting:{title:"会计基础",intro:"从三张报表理解企业经营活动如何转化为财务数字。",resources:[R("OpenStax Financial Accounting","https://openstax.org/details/books/principles-financial-accounting","入门","开放教材","基础代数"),R("MIT 15.515 Financial Accounting","https://ocw.mit.edu/courses/15-515-financial-accounting-fall-2003/","进阶"),R("MIT 15.535 Business Analysis","https://ocw.mit.edu/courses/15-535-business-analysis-using-financial-statements-spring-2003/","高级")]},
 math:{title:"数学与统计",intro:"建立理解经济模型、风险与定价所需的共同语言。",resources:[R("MIT 18.01 Calculus","https://ocw.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/","入门"),R("MIT 18.06 Linear Algebra","https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/","进阶"),R("MIT 18.650 Statistics","https://ocw.mit.edu/courses/18-650-statistics-for-applications-fall-2016/","高级")]},
 micro:{title:"微观经济学",intro:"研究个人、企业与市场如何在约束下做出选择。",resources:[R("MIT 14.01 Principles of Microeconomics","https://ocw.mit.edu/courses/14-01-principles-of-microeconomics-fall-2018/","入门"),R("MIT 14.04 Intermediate Microeconomics","https://ocw.mit.edu/courses/14-04-intermediate-microeconomic-theory-fall-2020/","进阶"),R("MIT 14.121 Microeconomic Theory I","https://ocw.mit.edu/courses/14-121-microeconomic-theory-i-fall-2015/","高级")]},
 macro:{title:"宏观经济学",intro:"理解增长、通胀、就业以及货币与财政政策。",resources:[R("MIT 14.02 Principles of Macroeconomics","https://ocw.mit.edu/courses/14-02-principles-of-macroeconomics-spring-2023/","入门"),R("MIT 14.06 Intermediate Macroeconomics","https://ocw.mit.edu/courses/14-06-intermediate-macroeconomic-theory-spring-2004/","进阶"),R("MIT 14.461 Advanced Macroeconomics","https://ocw.mit.edu/courses/14-461-advanced-macroeconomics-i-fall-2012/","高级")]},
 econometrics:{title:"计量经济学",intro:"把经济问题转化为可以使用数据检验的假设。",resources:[R("MIT 14.30 Statistical Methods","https://ocw.mit.edu/courses/14-30-introduction-to-statistical-methods-in-economics-spring-2009/","入门"),R("MIT 14.32 Econometrics","https://ocw.mit.edu/courses/14-32-econometrics-spring-2007/","进阶"),R("MIT 14.381 Statistical Method","https://ocw.mit.edu/courses/14-381-statistical-method-in-economics-fall-2018/","高级")]},
 corporate:{title:"公司金融",intro:"理解企业如何投资、融资、分配现金并管理风险。",resources:[R("OpenStax Principles of Finance","https://openstax.org/details/books/principles-finance","入门","开放教材"),R("Damodaran Corporate Finance","https://pages.stern.nyu.edu/~adamodar/New_Home_Page/cfshdesc.html","进阶"),R("MIT 15.402 Finance Theory II","https://ocw.mit.edu/courses/15-402-finance-theory-ii-spring-2003/","高级")]},
 investments:{title:"投资学",intro:"从风险与收益出发理解资产配置和市场运作。",resources:[R("Yale Financial Markets","https://oyc.yale.edu/economics/econ-252-11","入门"),R("MIT 15.401 Finance Theory I","https://ocw.mit.edu/courses/15-401-finance-theory-i-fall-2008/","进阶"),R("MIT 15.433 Investments","https://ocw.mit.edu/courses/15-433-investments-spring-2003/","高级")]},
 pricing:{title:"资产定价",intro:"研究风险为何以及如何获得补偿。",resources:[R("Yale Financial Theory","https://oyc.yale.edu/economics/econ-251","入门"),R("MIT 15.401 Finance Theory I","https://ocw.mit.edu/courses/15-401-finance-theory-i-fall-2008/","进阶"),R("Asset Pricing — John Cochrane","https://www.johnhcochrane.com/asset-pricing","高级","开放教材")]},
 "fixed-income":{title:"固定收益",intro:"理解债券、利率与信用风险的定价框架。",resources:[R("OpenStax Finance: Bonds","https://openstax.org/books/principles-finance/pages/10-introduction","入门","开放教材"),R("MIT 15.401 Finance Theory I","https://ocw.mit.edu/courses/15-401-finance-theory-i-fall-2008/","进阶"),R("MIT 15.433 Investments","https://ocw.mit.edu/courses/15-433-investments-spring-2003/","高级")]},
 valuation:{title:"企业研究与估值",intro:"把会计、公司金融和行业知识用于研究真实企业。",resources:[R("OpenStax Finance: Valuation","https://openstax.org/books/principles-finance/pages/11-introduction","入门","开放教材"),R("Damodaran Valuation","https://pages.stern.nyu.edu/~adamodar/New_Home_Page/equity.html","进阶"),R("MIT 15.535 Business Analysis","https://ocw.mit.edu/courses/15-535-business-analysis-using-financial-statements-spring-2003/","高级")]},
 empirical:{title:"实证金融",intro:"使用真实数据检验关于市场、公司和投资者的假设。",resources:[R("Causal Inference: The Mixtape","https://mixtape.scunning.com/","入门","开放教材"),R("MIT 14.32 Econometrics","https://ocw.mit.edu/courses/14-32-econometrics-spring-2007/","进阶"),R("MIT 14.387 Applied Econometrics","https://ocw.mit.edu/courses/14-387-applied-econometrics-mostly-harmless-big-data-fall-2014/","高级")]},
 "macro-research":{title:"宏观与政策研究",intro:"把宏观理论与公开数据结合，解释经济和政策变化。",resources:[R("FRED Economic Data","https://fred.stlouisfed.org/","入门","公开资料"),R("MIT 14.06 Intermediate Macroeconomics","https://ocw.mit.edu/courses/14-06-intermediate-macroeconomic-theory-spring-2004/","进阶"),R("MIT 14.461 Advanced Macroeconomics","https://ocw.mit.edu/courses/14-461-advanced-macroeconomics-i-fall-2012/","高级")]},
 risk:{title:"风险管理",intro:"识别、度量并沟通市场、信用与流动性风险。",resources:[R("OpenStax Principles of Finance","https://openstax.org/details/books/principles-finance","入门","开放教材"),R("MIT 15.401 Finance Theory I","https://ocw.mit.edu/courses/15-401-finance-theory-i-fall-2008/","进阶"),R("MIT 18.S096 Mathematics in Finance","https://ocw.mit.edu/courses/18-s096-topics-in-mathematics-with-applications-in-finance-fall-2013/","高级")]},
 behavioral:{title:"行为金融",intro:"研究认知偏差、激励和制度如何影响金融决策。",resources:[R("Yale Financial Markets","https://oyc.yale.edu/economics/econ-252-11","入门"),R("Behavioral Corporate Finance Survey","https://www.nber.org/papers/w17333","进阶","论文"),R("MIT 14.160 Behavioral Economics","https://ocw.mit.edu/courses/14-160-behavioral-economics-spring-2020/","高级")]},
 quant:{title:"量化研究",intro:"用编程、统计和可复现研究回答金融问题。",resources:[R("Python Data Science Handbook","https://jakevdp.github.io/PythonDataScienceHandbook/","入门","开放教材"),R("MIT 18.S096 Mathematics in Finance","https://ocw.mit.edu/courses/18-s096-topics-in-mathematics-with-applications-in-finance-fall-2013/","进阶"),R("MIT 15.433 Investments","https://ocw.mit.edu/courses/15-433-investments-spring-2003/","高级")]},
 projects:{title:"研究方法与项目",intro:"用明确问题、数据、方法和可复现成果检验理解。",resources:[R("The Turing Way","https://the-turing-way.netlify.app/","入门","开放教材"),R("MIT OpenCourseWare","https://ocw.mit.edu/","进阶","项目资料")]},
 books:{title:"书单与资源",intro:"选择结构完整、练习充分且公开可访问的课程和教材。",resources:[R("OpenStax Economics","https://openstax.org/subjects/business","入门","开放教材"),R("MIT OpenCourseWare Economics","https://ocw.mit.edu/search/?d=Economics","进阶","课程库")]}
};
