import{r,type Resource,type SubjectConfig,type Topic}from"./subjectTypes";
type Course=[string,string,string,Resource[]];
type Track={slug:string;name:string;en:string;intro:string;caution:string;courses:Course[];tools:SubjectConfig["tools"];books:SubjectConfig["books"];portals:SubjectConfig["portals"]};
const start=["开始之前",[["intro","本站目的"],["how","如何使用本站"],["plan","学习规划"]]] as const;
const makeTrack=(track:Track):SubjectConfig=>{
 const topics:Record<string,Topic>={tools:{title:"学习工具",intro:`围绕${track.name}建立计算、仿真、设计和实验环境。`,resources:[]},projects:{title:"项目与进阶方向",intro:`以${track.name}的真实约束完成建模、设计、实现、测试和复盘。下面的起点分别对应本学科的核心课程，适合从小型复现逐步发展为综合项目。`,resources:track.courses.map(([, , ,resources])=>resources[0])},books:{title:"书单与资源",intro:"集中查看开放教材与大学官方课程。",resources:[]}};
 track.courses.forEach(([id,title,intro,resources])=>{topics[id]={title,intro,resources}});
 const phases=track.courses.map(([id,title,intro],index)=>({time:index===0?"2–3 个月":"3–5 个月",title:`学习${title}`,goal:intro,learn:`完成${title}的主课程、例题和核心习题。`,done:`能独立解释${title}的关键模型，并完成一次计算、仿真或实验。`,link:id}));
 phases.push({time:"持续",title:"完成专业项目",goal:"把分散课程连接为可验证的工程成果。",learn:"需求、模型、设计、测试、数据、文档与安全。",done:"发布可复现的项目文件、测试结果和改进记录。",link:"projects"});
 return{slug:`engineering/${track.slug}`,name:track.name,en:track.en,intro:track.intro,caution:track.caution,groups:[start,["起点",[["tools","学习工具"]]],["核心课程",track.courses.map(([id,title])=>[id,title] as const)],["实践与资源",[["projects","项目与进阶方向"],["books","书单与资源"]]]],topics,phases,tools:track.tools,books:track.books,portals:track.portals};
};
const commonPortals=(name:string,query:string):SubjectConfig["portals"]=>[["MIT",`MIT OCW ${name}`,`https://ocw.mit.edu/search/?q=${query}`,`检索 ${name} 官方公开课程、讲义与作业。`]];

export const electricalEngineering=makeTrack({slug:"electrical",name:"电子与电气工程",en:"ELECTRICAL ENGINEERING",intro:"电子与电气工程研究电能与信息如何被产生、传输、处理和控制，主线从电路进入信号、器件、电磁、通信与能源系统。",caution:"电气实验必须区分低压原型与高压系统。自学只进行安全低压实验；电网、电机和高功率设备需要专业指导。",courses:[
 ["circuits","电路与电子学","从电压、电流和网络定律进入晶体管、放大器与模拟电路。",[r("All About Circuits Textbook","https://www.allaboutcircuits.com/textbook/","入门","开放教材","代数与基础物理","免费电路教材，适合建立元件和网络直觉。"),r("MIT 6.002 Circuits and Electronics","https://ocw.mit.edu/courses/6-002-circuits-and-electronics-spring-2007/","进阶","公开课","微积分与基础电磁学","系统学习电路、MOS 管、放大器和动态网络。"),r("MIT 6.012 Microelectronic Devices and Circuits","https://ocw.mit.edu/courses/6-012-microelectronic-devices-and-circuits-fall-2009/","高级","公开课","半导体物理与电路","从器件物理连接到微电子电路设计。")]],
 ["signals","信号与系统","学习连续与离散信号、系统响应、傅里叶和采样。",[r("Signals and Systems — LibreTexts","https://eng.libretexts.org/Bookshelves/Electrical_Engineering/Signal_Processing_and_Modeling/Signals_and_Systems_(Baraniuk_et_al.)","入门","开放教材","微积分与复数","用开放教材建立时域和频域语言。"),r("MIT RES.6-007 Signals and Systems","https://ocw.mit.edu/resources/res-6-007-signals-and-systems-spring-2011/","进阶","公开课","微分方程与线性代数","完整视频、讲义和习题覆盖 LTI、变换与滤波。"),r("MIT 6.341 Discrete-Time Signal Processing","https://ocw.mit.edu/courses/6-341-discrete-time-signal-processing-fall-2005/","高级","公开课","信号与系统","深入离散滤波器、频谱和多速率处理。")]],
 ["fields-power","电磁场与能源系统","理解场、波、电机、功率电子和电能转换。",[r("OpenStax University Physics II","https://openstax.org/details/books/university-physics-volume-2","入门","开放教材","微积分与力学","建立静电、磁场、电磁感应和交流电基础。"),r("MIT 6.013 Electromagnetics and Applications","https://ocw.mit.edu/courses/6-013-electromagnetics-and-applications-fall-2005/","进阶","公开课","矢量分析与微分方程","从 Maxwell 方程进入传输线、波与器件。"),r("MIT Power Electronics","https://ocw.mit.edu/search/?q=power%20electronics","高级","公开课","电路、控制与电磁学","研究开关变换器、驱动和能源系统。")]],
 ["communication","通信与数字系统","把信号、概率和硬件连接到可靠的信息传输。",[r("MIT 6.02 Introduction to EECS II","https://ocw.mit.edu/courses/6-02-introduction-to-eecs-ii-digital-communication-systems-fall-2012/","入门","公开课","编程、概率与信号基础","以数字通信网络建立编码和噪声直觉。"),r("MIT 6.450 Principles of Digital Communications I","https://ocw.mit.edu/courses/6-450-principles-of-digital-communications-i-fall-2006/","进阶","公开课","概率与信号系统","系统学习调制、检测、编码与信道。"),r("MIT 6.451 Principles of Digital Communication II","https://ocw.mit.edu/courses/6-451-principles-of-digital-communication-ii-spring-2005/","高级","公开课","数字通信 I","深入编码理论和现代通信系统。")]]],tools:[["电路与测量",[["LTspice","https://www.analog.com/en/resources/design-tools-and-calculators/ltspice-simulator.html","模拟电路仿真"],["KiCad","https://www.kicad.org/","原理图与 PCB 设计"],["Arduino","https://www.arduino.cc/","安全低压嵌入式实验"]]]],books:[["All About Circuits","https://www.allaboutcircuits.com/textbook/","电路 · 入门","免费在线电路教材。"],["OpenStax University Physics II","https://openstax.org/details/books/university-physics-volume-2","电磁 · 入门","开放电磁学基础。"]],portals:commonPortals("Electrical Engineering","electrical%20engineering")});

export const mechanicalEngineering=makeTrack({slug:"mechanical",name:"机械工程",en:"MECHANICAL ENGINEERING",intro:"机械工程研究力、运动、能量、材料和制造如何共同形成可靠的机器与产品。课程围绕固体力学、热流体、动力学和机械设计展开。",caution:"机械项目涉及旋转件、载荷、热源和加工设备。先做低能量原型，并为结构强度、防护和失效模式保留安全裕度。",courses:[
 ["mechanics","工程力学与固体力学","从受力、运动和材料变形分析机械构件。",[r("OpenStax University Physics I","https://openstax.org/details/books/university-physics-volume-1","入门","开放教材","微积分","复习力学、转动、振动和流体基础。"),r("MIT 2.001 Mechanics & Materials I","https://ocw.mit.edu/courses/2-001-mechanics-materials-i-fall-2006/","进阶","公开课","静力学与微积分","学习载荷、应力、应变和结构响应。"),r("MIT 3.11 Mechanics of Materials","https://ocw.mit.edu/courses/3-11-mechanics-of-materials-fall-1999/","高级","公开课","材料力学","深入梁、扭转、塑性和失效。")]],
 ["thermofluids","热力学与流体力学","研究能量转换、流动、传热和热系统。",[r("Engineering Thermodynamics — LibreTexts","https://eng.libretexts.org/Bookshelves/Mechanical_Engineering/Engineering_Thermodynamics_(Mitchell)","入门","开放教材","微积分与基础物理","从状态量和能量守恒进入工程热力学。"),r("MIT 2.005 Thermal-Fluids Engineering I","https://ocw.mit.edu/courses/2-005-thermal-fluids-engineering-i-fall-2006/","进阶","公开课","热力学与微分方程","连接控制体、流体和热过程。"),r("MIT 2.006 Thermal-Fluids Engineering II","https://ocw.mit.edu/courses/2-006-thermal-fluids-engineering-ii-spring-2008/","高级","公开课","热流体 I","深入传热、粘性流与工程系统。")]],
 ["dynamics","动力学、振动与控制","建立机械系统的运动模型并分析稳定性和响应。",[r("MIT 2.003 Modeling Dynamics and Control I","https://ocw.mit.edu/courses/2-003-modeling-dynamics-and-control-i-spring-2005/","入门","公开课","力学与微分方程","从集中参数模型进入机械动力学。"),r("Feedback Systems","https://fbsbook.org/","进阶","开放教材","线性代数与微分方程","学习反馈、稳定性和控制设计。"),r("Underactuated Robotics","https://underactuated.mit.edu/","高级","公开讲义","动力学、控制与优化","深入非线性机械系统和机器人。")]],
 ["design","机械设计与制造","把功能、载荷、材料、公差和制造过程转化为实体产品。",[r("FreeCAD Documentation","https://wiki.freecad.org/Getting_started","入门","公开讲义","无需前置","学习参数化建模并表达机械结构。"),r("MIT 2.007 Design and Manufacturing I","https://ocw.mit.edu/courses/2-007-design-and-manufacturing-i-spring-2009/","进阶","公开课","力学、材料与制图","通过机器人项目完成设计和制造。"),r("MIT 2.008 Design and Manufacturing II","https://ocw.mit.edu/courses/2-008-design-and-manufacturing-ii-spring-2004/","高级","公开课","机械设计与制造基础","进入工艺规划、生产和质量控制。")]]],tools:[["机械设计",[["FreeCAD","https://www.freecad.org/","参数化 CAD"],["Onshape Education","https://www.onshape.com/en/education/","浏览器协作 CAD"],["GNU Octave","https://octave.org/","动力学与热流体计算"]]]],books:[["OpenStax University Physics I","https://openstax.org/details/books/university-physics-volume-1","力学 · 入门","开放大学物理教材。"],["Engineering Thermodynamics","https://eng.libretexts.org/Bookshelves/Mechanical_Engineering/Engineering_Thermodynamics_(Mitchell)","热力学 · 进阶","免费工程热力学教材。"]],portals:commonPortals("Mechanical Engineering","mechanical%20engineering")});

export const computerEngineering=makeTrack({slug:"computer",name:"计算机工程",en:"COMPUTER ENGINEERING",intro:"计算机工程位于电子硬件与计算机科学之间，研究数字逻辑、处理器、存储、嵌入式设备和软硬件协同。",caution:"不要把计算机工程等同于一般编程。核心成果应能解释代码如何经过指令集、处理器、存储和接口在真实硬件上运行。",courses:[
 ["digital","数字逻辑与硬件描述","从布尔逻辑、状态机和 HDL 构建数字系统。",[r("Nand2Tetris Part I","https://www.nand2tetris.org/course","入门","项目平台","基础编程","从逻辑门逐步构建 CPU 和计算机。"),r("MIT 6.004 Computation Structures","https://ocw.mit.edu/courses/6-004-computation-structures-spring-2017/","进阶","公开课","编程与基础电路","系统学习数字逻辑、指令与处理器。"),r("MIT 6.111 Introductory Digital Systems Laboratory","https://ocw.mit.edu/courses/6-111-introductory-digital-systems-laboratory-spring-2006/","高级","公开课","数字逻辑与 HDL","通过 FPGA 完成复杂数字系统。")]],
 ["architecture","计算机组成与体系结构","理解指令集、流水线、缓存、虚拟内存与并行。",[r("Berkeley CS61C","https://cs61c.org/","入门","公开课","C 与数据结构","从 C、汇编和 RISC-V 进入机器结构。"),r("MIT 6.823 Computer System Architecture","https://ocw.mit.edu/courses/6-823-computer-system-architecture-fall-2005/","进阶","公开课","数字逻辑与组成原理","系统学习流水线、存储层次和多处理器。"),r("Berkeley CS152","https://cs152.berkeley.edu/","高级","公开课","体系结构基础","通过处理器设计深入现代体系结构。")]],
 ["embedded","嵌入式与实时系统","连接微控制器、传感器、接口、操作系统和实时约束。",[r("Embedded Systems — Shape the World","https://users.ece.utexas.edu/~valvano/Volume1/","入门","开放教材","C 与基础电路","从微控制器 I/O 和中断开始实践。"),r("MIT 6.S081 Operating System Engineering","https://pdos.csail.mit.edu/6.S081/2021/","进阶","公开课","C、体系结构与调试","通过 xv6 理解硬件与操作系统接口。"),r("MIT 6.182 Mobile and Sensor Computing","https://catalog.mit.edu/subjects/6/","高级","公开课","嵌入式、网络与概率","进入传感、移动和受限计算系统。")]],
 ["hardware-systems","硬件系统与协同设计","综合处理器、接口、软件、验证与性能工程。",[r("RISC-V Specifications","https://riscv.org/specifications/","入门","公开讲义","组成原理","阅读开放指令集规范并实现小型实验。"),r("OpenROAD Project","https://theopenroadproject.org/","进阶","项目平台","HDL 与数字电路","了解开放芯片设计流程。"),r("MIT 6.2050 Digital Systems Laboratory","https://catalog.mit.edu/subjects/6/","高级","公开课","数字系统与计算机组成","围绕 FPGA、接口和验证完成系统项目。")]]],tools:[["硬件开发",[["Logisim Evolution","https://github.com/logisim-evolution/logisim-evolution","数字电路仿真"],["RISC-V","https://riscv.org/","开放指令集资料"],["PlatformIO","https://platformio.org/","嵌入式开发环境"]]]],books:[["Nand2Tetris","https://www.nand2tetris.org/","数字系统 · 入门","免费课程与项目。"],["RISC-V Specifications","https://riscv.org/specifications/","体系结构 · 进阶","开放指令集规范。"]],portals:[["UIUC","UIUC Computer Engineering BS","https://catalog.illinois.edu/undergraduate/engineering/computer-engineering-bs/","计算机工程核心课程与专业方向。"],...commonPortals("Computer Engineering","computer%20engineering")]});

export const aerospaceEngineering=makeTrack({slug:"aerospace",name:"航空航天工程",en:"AEROSPACE ENGINEERING",intro:"航空航天工程围绕飞机、火箭、卫星和自主飞行器，整合空气动力学、推进、结构、飞行动力学与系统设计。",caution:"飞行器设计对安全、法规和验证要求极高。自学应以仿真、公开数据和低风险模型为主，不开展未经指导的推进、高压或载人实验。",courses:[
 ["aerodynamics","空气动力学与流体","研究翼型、边界层、可压缩流和飞行性能。",[r("NASA Beginner’s Guide to Aeronautics","https://www.nasa.gov/stem-content/beginners-guide-to-aeronautics/","入门","公开讲义","代数与基础物理","建立升力、阻力和飞行的直觉。"),r("MIT 16.100 Aerodynamics","https://ocw.mit.edu/courses/16-100-aerodynamics-fall-2005/","进阶","公开课","流体力学与微分方程","系统学习势流、翼型和有限翼。"),r("MIT Compressible Flow","https://ocw.mit.edu/search/?q=compressible%20flow","高级","公开课","热力学与流体力学","进入激波、喷管和高速空气动力学。")]],
 ["structures","航空航天结构","分析轻质结构、材料、载荷、振动和结构失效。",[r("MIT 16.01 Unified Engineering: Materials and Structures","https://ocw.mit.edu/courses/16-01-unified-engineering-i-ii-iii-iv-fall-2005-spring-2006/","入门","公开课","力学与微积分","在飞行器背景中学习材料与结构。"),r("MIT Aerospace Structures","https://ocw.mit.edu/search/?q=aerospace%20structures","进阶","公开课","材料力学","研究薄壁结构、屈曲和轻量化。"),r("NASA Technical Reports Server","https://ntrs.nasa.gov/","高级","项目平台","结构、统计与文献阅读","使用真实技术报告研究结构验证与失效。")]],
 ["propulsion","航空与航天推进","连接热力学、流体、燃烧、喷气发动机和火箭。",[r("NASA Beginner’s Guide to Propulsion","https://www.grc.nasa.gov/www/k-12/airplane/bgp.html","入门","公开讲义","基础热学与流体","理解喷气和火箭推进的主要部件。"),r("MIT 16.50 Introduction to Propulsion Systems","https://ocw.mit.edu/courses/16-50-introduction-to-propulsion-systems-spring-2012/","进阶","公开课","热力学与流体力学","覆盖热机、喷气和火箭推进。"),r("MIT Rocket Propulsion","https://ocw.mit.edu/search/?q=rocket%20propulsion","高级","公开课","可压缩流与燃烧","深入火箭发动机性能与设计。")]],
 ["flight-space","飞行动力学、控制与航天系统","研究稳定性、制导控制、轨道和任务设计。",[r("MIT 16.00 Introduction to Aerospace Engineering and Design","https://ocw.mit.edu/courses/16-00-introduction-to-aerospace-engineering-and-design-spring-2003/","入门","公开课","力学与微积分","通过综合设计认识航空与航天系统。"),r("MIT 16.07 Dynamics","https://ocw.mit.edu/courses/16-07-dynamics-fall-2009/","进阶","公开课","经典力学与微分方程","学习飞行器动力学所需的运动学和动力学。"),r("MIT 16.346 Astrodynamics","https://ocw.mit.edu/courses/16-346-astrodynamics-fall-2008/","高级","公开课","动力学、控制与数值方法","进入轨道、摄动和航天任务分析。")]]],tools:[["航空航天计算",[["OpenVSP","https://openvsp.org/","NASA 开源飞行器几何工具"],["SU2","https://su2code.github.io/","开源 CFD 与设计"],["GMAT","https://gmat.atlassian.net/wiki/spaces/GW/overview","开源航天任务分析"]]]],books:[["NASA Beginner’s Guide","https://www.nasa.gov/stem-content/beginners-guide-to-aeronautics/","航空 · 入门","NASA 飞行与推进资料。"],["MIT Unified Engineering","https://ocw.mit.edu/courses/16-01-unified-engineering-i-ii-iii-iv-fall-2005-spring-2006/","综合 · 进阶","MIT 航空航天核心课程。"]],portals:[["MIT","MIT AeroAstro Curriculum","https://catalog.mit.edu/schools/engineering/aeronautics-astronautics/","航空航天本科核心与专业方向。"],...commonPortals("Aerospace Engineering","aerospace%20engineering")]});

export const controlEngineering=makeTrack({slug:"systems",name:"控制与系统工程",en:"CONTROL AND SYSTEMS ENGINEERING",intro:"控制与系统工程研究动态系统如何被建模、估计、反馈和优化，服务于机器人、飞行器、能源和复杂工程系统。",caution:"控制器在仿真中稳定，不代表真实系统安全。必须考虑传感误差、执行器限制、时延、饱和与失效保护。",courses:[
 ["modeling","动态系统建模","用微分方程、状态空间和数据描述系统动态。",[r("MIT 6.01SC Signals and Systems","https://ocw.mit.edu/courses/6-01sc-introduction-to-electrical-engineering-and-computer-science-i-spring-2011/pages/unit-2-signals-and-systems/","入门","公开课","微积分与编程","从状态机和系统响应建立模型直觉。"),r("MIT RES.6-007 Signals and Systems","https://ocw.mit.edu/resources/res-6-007-signals-and-systems-spring-2011/","进阶","公开课","微分方程与线性代数","学习系统、变换与频率响应。"),r("MIT System Identification","https://ocw.mit.edu/search/?q=system%20identification","高级","公开课","概率、优化与动态系统","从实验数据估计模型和不确定性。")]],
 ["feedback","反馈控制","学习稳定性、PID、频域方法、状态反馈和鲁棒性。",[r("Feedback Systems","https://fbsbook.org/","入门","开放教材","微积分与线性代数","开放教材连接反馈直觉和数学。"),r("MIT 6.302 Feedback Systems","https://ocw.mit.edu/courses/6-302-feedback-systems-spring-2007/","进阶","公开课","信号系统与微分方程","系统学习频率设计和反馈实现。"),r("MIT 16.30 Feedback Control Systems","https://catalog.mit.edu/subjects/16/","高级","公开课","状态空间与概率","进入多变量控制、估计和鲁棒性。")]],
 ["estimation","状态估计与最优控制","在噪声和约束下进行估计、规划与决策。",[r("Kalman Filter — Welch & Bishop","https://www.cs.unc.edu/~welch/media/pdf/kalman_intro.pdf","入门","公开讲义","概率与线性代数","简明建立卡尔曼滤波概念。"),r("Stanford EE363 Linear Dynamical Systems","https://web.stanford.edu/class/ee363/","进阶","公开课","状态空间与优化","学习估计、LQR 和线性动态系统。"),r("MIT Dynamic Systems and Control","https://catalog.mit.edu/subjects/6/","高级","公开课","控制、概率与优化","深入多变量、最优与鲁棒控制。")]],
 ["robotics","机器人与系统集成","把感知、规划、控制、接口和安全连接为完整系统。",[r("Modern Robotics","https://modernrobotics.northwestern.edu/nu-gm-book-resource/","入门","开放教材","线性代数与编程","免费教材和视频覆盖运动学与控制。"),r("MIT Underactuated Robotics","https://underactuated.mit.edu/","进阶","公开讲义","动力学、控制与优化","研究非线性机器人和运动规划。"),r("MIT Robotics: Science and Systems","https://ocw.mit.edu/search/?q=robotics%20science%20systems","高级","公开课","机器人基础与概率","综合定位、规划、感知和系统实现。")]]],tools:[["建模与控制",[["Python Control Systems Library","https://python-control.readthedocs.io/","控制分析与设计"],["GNU Octave","https://octave.org/","矩阵与动态系统计算"],["ROS","https://www.ros.org/","机器人系统集成"]]]],books:[["Feedback Systems","https://fbsbook.org/","控制 · 入门","公开反馈控制教材。"],["Modern Robotics","https://modernrobotics.northwestern.edu/nu-gm-book-resource/","机器人 · 进阶","免费教材、视频和代码。"]],portals:commonPortals("Control Systems","control%20systems")});

export const materialsEngineering=makeTrack({slug:"materials",name:"材料工程",en:"MATERIALS SCIENCE AND ENGINEERING",intro:"材料工程以加工—结构—性能—应用为主线，研究金属、陶瓷、聚合物、半导体和复合材料如何被设计与验证。",caution:"材料实验可能涉及高温、压力、化学品和制样设备。自学以数据、仿真和公开案例为主，实验必须遵守专业安全规范。",courses:[
 ["structure","材料结构与热力学","从原子键、晶体和缺陷进入相平衡与材料稳定性。",[r("MIT 3.091 Introduction to Solid-State Chemistry","https://ocw.mit.edu/courses/3-091-introduction-to-solid-state-chemistry-fall-2018/","入门","公开课","普通化学与基础物理","建立固体结构和材料性质基础。"),r("MIT 3.020 Thermodynamics of Materials","https://ocw.mit.edu/courses/3-020-thermodynamics-of-materials-spring-2021/","进阶","公开课","热力学与微积分","学习相平衡、化学势和材料稳定性。"),r("MIT Phase Transformations","https://ocw.mit.edu/search/?q=phase%20transformations%20materials","高级","公开课","材料热力学与动力学","深入形核、长大和微结构演化。")]],
 ["properties","材料力学与功能性质","理解微观结构如何决定力、电、磁、光和热性质。",[r("OpenStax University Physics","https://openstax.org/details/books/university-physics-volume-1","入门","开放教材","微积分","补充力学、电磁和热学基础。"),r("MIT 3.11 Mechanics of Materials","https://ocw.mit.edu/courses/3-11-mechanics-of-materials-fall-1999/","进阶","公开课","静力学与材料结构","学习弹塑性、断裂和结构响应。"),r("MIT Electronic, Optical and Magnetic Properties","https://ocw.mit.edu/search/?q=electronic%20optical%20magnetic%20properties%20materials","高级","公开课","量子与固体基础","连接电子结构与功能材料。")]],
 ["processing","材料加工与微结构","研究凝固、热处理、成形、烧结和聚合物加工。",[r("DoITPoMS Teaching Resources","https://www.doitpoms.ac.uk/","入门","公开讲义","材料结构基础","剑桥材料教学模块和交互内容。"),r("MIT 3.044 Materials Processing","https://ocw.mit.edu/courses/3-044-materials-processing-spring-2013/","进阶","公开课","热力学、流体与传热","用输运过程理解材料加工。"),r("MIT Microstructural Evolution","https://ocw.mit.edu/search/?q=microstructural%20evolution","高级","公开课","扩散与相变","研究加工路径如何塑造微结构。")]],
 ["characterization","材料表征、选材与设计","用实验和计算识别结构、性质与失效，并针对工况选材。",[r("Materials Project","https://next-gen.materialsproject.org/","入门","项目平台","材料基础与数据分析","探索开放材料结构和计算性质。"),r("MIT Materials Laboratory","https://ocw.mit.edu/search/?q=materials%20laboratory","进阶","公开课","材料结构与统计","学习表征、实验设计和数据解释。"),r("NIST Materials Data Repository","https://materialsdata.nist.gov/","高级","项目平台","材料学、统计与编程","使用权威数据完成材料比较或失效研究。")]]],tools:[["材料数据与建模",[["Materials Project","https://next-gen.materialsproject.org/","开放计算材料数据库"],["VESTA","https://jp-minerals.org/vesta/en/","晶体结构可视化"],["ImageJ","https://imagej.net/","显微图像分析"]]]],books:[["DoITPoMS","https://www.doitpoms.ac.uk/","材料 · 入门","剑桥大学开放教学模块。"],["MIT 3.091","https://ocw.mit.edu/courses/3-091-introduction-to-solid-state-chemistry-fall-2018/","固体 · 入门","完整公开课程。"]],portals:[["MIT","MIT Materials Curriculum","https://catalog.mit.edu/degree-charts/materials-science-engineering-course-3/","材料工程本科课程结构。"],...commonPortals("Materials Science","materials%20science")]});

export const engineeringTracks=[electricalEngineering,mechanicalEngineering,computerEngineering,aerospaceEngineering,controlEngineering,materialsEngineering];
