import {useEffect,useRef,useState} from "react";
type Node={id:string;label:string,group:string,x:number,y:number,size:number};
const colors:Record<string,string>={数学:"#8794ad",计算机:"#789b96",经济学:"#aa9474",金融:"#78977f",物理:"#9187a5",工程:"#a78178",交叉领域:"#505860"};
const nodes:Node[]=[
 {id:"math",label:"数学",group:"数学",x:.16,y:.2,size:9},{id:"cs",label:"计算机",group:"计算机",x:.5,y:.12,size:9},{id:"physics",label:"物理",group:"物理",x:.82,y:.21,size:9},{id:"econ",label:"经济学",group:"经济学",x:.13,y:.72,size:9},{id:"finance",label:"金融",group:"金融",x:.48,y:.84,size:10},{id:"engineering",label:"工程",group:"工程",x:.85,y:.72,size:9},
 {id:"stats",label:"概率统计",group:"数学",x:.26,y:.35,size:5},{id:"opt",label:"优化",group:"数学",x:.34,y:.19,size:5},{id:"algo",label:"算法",group:"计算机",x:.55,y:.3,size:5},{id:"data",label:"数据科学",group:"计算机",x:.39,y:.4,size:5},{id:"mechanics",label:"力学",group:"物理",x:.75,y:.38,size:5},{id:"dynamics",label:"动力系统",group:"物理",x:.68,y:.52,size:5},{id:"micro",label:"微观经济学",group:"经济学",x:.25,y:.66,size:5},{id:"macro",label:"宏观经济学",group:"经济学",x:.24,y:.82,size:5},{id:"pricing",label:"资产定价",group:"金融",x:.4,y:.68,size:5},{id:"corp",label:"公司金融",group:"金融",x:.59,y:.73,size:5},{id:"control",label:"控制理论",group:"工程",x:.78,y:.57,size:5},
 {id:"ml",label:"机器学习",group:"交叉领域",x:.49,y:.43,size:8},{id:"metrics",label:"计量经济学",group:"交叉领域",x:.32,y:.55,size:8},{id:"quant",label:"量化研究",group:"交叉领域",x:.47,y:.59,size:8},{id:"fineng",label:"金融工程",group:"交叉领域",x:.61,y:.59,size:8},{id:"complex",label:"复杂系统",group:"交叉领域",x:.65,y:.4,size:8},{id:"robot",label:"机器人",group:"交叉领域",x:.76,y:.47,size:8}
];
const edges=[["math","stats"],["math","opt"],["cs","algo"],["cs","data"],["physics","mechanics"],["physics","dynamics"],["econ","micro"],["econ","macro"],["finance","pricing"],["finance","corp"],["engineering","control"],["stats","metrics"],["data","metrics"],["micro","metrics"],["stats","ml"],["opt","ml"],["algo","ml"],["data","ml"],["stats","quant"],["data","quant"],["metrics","quant"],["pricing","quant"],["opt","fineng"],["algo","fineng"],["pricing","fineng"],["dynamics","complex"],["macro","complex"],["algo","complex"],["mechanics","robot"],["control","robot"],["algo","robot"],["complex","robot"],["fineng","engineering"]];
export default function KnowledgeGraph(){const ref=useRef<HTMLCanvasElement>(null);const [active,setActive]=useState<Node|null>(null);useEffect(()=>{const canvas=ref.current;if(!canvas)return;const draw=()=>{const rect=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;const c=canvas.getContext("2d")!;c.scale(dpr,dpr);c.clearRect(0,0,rect.width,rect.height);const pos=(n:Node)=>({x:n.x*rect.width,y:n.y*rect.height});c.strokeStyle="#d8dcda";c.lineWidth=1;for(const [a,b] of edges){const p=pos(nodes.find(n=>n.id===a)!),q=pos(nodes.find(n=>n.id===b)!);c.beginPath();c.moveTo(p.x,p.y);c.lineTo(q.x,q.y);c.stroke()}for(const n of nodes){const p=pos(n),selected=active?.id===n.id;c.beginPath();c.arc(p.x,p.y,n.size+(selected?3:0),0,Math.PI*2);c.fillStyle=colors[n.group];c.fill();if(selected){c.strokeStyle="#fff";c.lineWidth=2;c.stroke()}if(n.size>=8||selected){c.font=`${selected?600:500} 12px -apple-system, sans-serif`;c.fillStyle="#343a40";c.fillText(n.label,p.x+n.size+7,p.y+4)}}};draw();const observer=new ResizeObserver(draw);observer.observe(canvas);return()=>observer.disconnect()},[active]);const pick=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;let found:Node|null=null,dist=22;for(const n of nodes){const d=Math.hypot(x-n.x*r.width,y-n.y*r.height);if(d<dist){dist=d;found=n}}setActive(found)};return <section className="knowledge-section" id="knowledge-graph"><div className="knowledge-heading"><small>KNOWLEDGE GRAPH</small><h2>知识不是孤立的章节</h2><p>每个点代表一个知识，线表示它们之间的依赖或应用关系。高阶领域通常位于多个基础学科的交汇处。</p></div><div className="graph-shell"><canvas ref={ref} onPointerMove={pick} onPointerDown={pick} onPointerLeave={()=>setActive(null)} role="img" aria-label="数学、计算机、经济学、金融、物理与工程的跨学科知识图谱"/><div className="graph-tooltip" aria-live="polite">{active?<><b>{active.label}</b><span>{active.group}</span></>:<><b>探索知识图谱</b><span>悬停或点击任意节点</span></>}</div></div><div className="graph-legend">{Object.entries(colors).map(([name,color])=><span key={name}><i style={{background:color}}/>{name}</span>)}</div><p className="graph-note">这是知识图谱的第一层。未来每个节点将连接到对应课程、教材、论文和实践项目。</p></section>}
