import {r,type SubjectConfig,type Topic} from "./subjectTypes";
const t=(title:string,intro:string,resources:ReturnType<typeof r>[]):Topic=>({title,intro,resources});
const start=["开始之前",[["intro","本站目的"],["how","如何使用本站"],["plan","学习规划"]]] as const;
const topics:Record<string,Topic>={
 tools:t("学习工具","结合语料、词典、发音、间隔复习和真实交流建立语言能力。",[]),
 methods:t("语言学习方法","用可理解输入、主动回忆、输出反馈和长期复习组织学习。",[r("Learning How to Learn","https://www.coursera.org/learn/learning-how-to-learn","入门","公开课","无需前置","建立记忆、专注和练习方法。"),r("MIT Global Languages","https://languages.mit.edu/","进阶","项目平台","正在学习一门语言","利用大学语言资源规划听说读写训练。"),r("MIT Second Language Acquisition","https://ocw.mit.edu/search/?q=second%20language%20acquisition","高级","公开课","语言学与研究方法","从研究证据理解输入、互动、反馈与习得。")]),
 linguistics:t("语言学","科学研究语音、词、句法、意义、习得和语言变化。",[r("Essentials of Linguistics 2e","https://opentextbc.ca/essentialsoflinguistics2/","入门","开放教材","无需前置","配有视频和练习的完整开放导论教材。"),r("MIT 24.900 Introduction to Linguistics","https://ocw.mit.edu/courses/24-900-introduction-to-linguistics-spring-2022/","进阶","公开课","无需前置","覆盖音系、形态、句法、语义、习得和变化。"),r("MIT Advanced Linguistics","https://ocw.mit.edu/search/?d=Linguistics","高级","公开课","语言学导论与逻辑基础","进入句法理论、语义学、音系学和语言哲学。")]),
 sound:t("语音、语法与意义","分析语言声音、词法、句法结构与语义组合。",[r("UCLA Phonetics Lab Data","https://www.phonetics.ucla.edu/","入门","项目平台","语言学导论","通过真实录音和音标练习语音辨析。"),r("MIT Syntax and Semantics","https://ocw.mit.edu/search/?q=syntax%20semantics","进阶","公开课","语言学导论与逻辑","学习结构分析、组合意义和论证。"),r("Praat","https://www.fon.hum.uva.nl/praat/","高级","项目平台","语音学与基础统计","测量基频、共振峰和时长并完成声学分析。")]),
 chinese:t("汉语","从普通话语音和高频表达进入汉字阅读、写作与文化语境。",[r("MIT Learning Chinese: A Foundation Course","https://ocw.mit.edu/courses/res-21g-003-learning-chinese-a-foundation-course-in-mandarin-spring-2011/","入门","公开课","无需前置","完整在线教材和音频，将口语与汉字学习分阶段组织。"),r("MIT Chinese I","https://ocw.mit.edu/courses/21g-101-chinese-i-regular-fall-2014/","进阶","公开课","掌握拼音和基础表达","以准备、听说和课堂互动建立交际能力。"),r("Chinese Text Project","https://ctext.org/","高级","项目平台","现代汉语阅读与基础文言","利用双语古籍和检索工具进入古典汉语。")]),
 english:t("英语","围绕真实输入、学术阅读、写作、表达和修订建立综合能力。",[r("USA Learns English Courses","https://www.usalearns.org/","入门","公开课","无需前置","免费练习生活英语的听力、词汇和基本表达。"),r("MIT High-Intermediate Academic Communication","https://ocw.mit.edu/courses/21g-213-high-intermediate-academic-communication-spring-2004/","进阶","公开课","英语 B1–B2 左右","强化学术词汇、口语和写作表达。"),r("MIT Advanced Writing for Science and Engineering","https://ocw.mit.edu/courses/21g-225-advanced-workshop-in-writing-for-science-and-engineering-els-spring-2016/","高级","公开课","英语 B2–C1 与专业知识","训练专业写作、演讲和面向受众的表达。")]),
 society:t("社会语言学与语言变化","理解方言、身份、权力、接触、历史变化和语言政策。",[r("Essentials of Linguistics: Language and Society","https://opentextbc.ca/essentialsoflinguistics2/","入门","开放教材","语言学导论","从变体和社会意义建立基本框架。"),r("MIT Language and Society","https://ocw.mit.edu/search/?q=language%20society","进阶","公开课","语言学导论与社会科学基础","研究方言、身份、政策和语言接触。"),r("WALS Online","https://wals.info/","高级","项目平台","类型学、统计与地图基础","使用世界语言特征数据库开展跨语言比较。")]),
 computational:t("计算语言学","用规则、统计和机器学习处理文本与语音。",[r("NLTK Book","https://www.nltk.org/book/","入门","开放教材","Python 基础","通过可运行示例学习分词、标注、分类和语料分析。"),r("Stanford CS224N","https://web.stanford.edu/class/cs224n/","进阶","公开课","Python、线性代数、概率与机器学习","系统学习现代自然语言处理。"),r("Speech and Language Processing","https://web.stanford.edu/~jurafsky/slp3/","高级","开放教材","NLP 与深度学习","作者公开的教材草稿，覆盖语言与语音技术。")]),
 projects:t("项目与进阶方向","用语料、录音、写作作品或真实交流检验学习成果。",[r("Common Voice","https://commonvoice.mozilla.org/","入门","项目平台","任意语言基础","参与开放语音数据并观察口音差异。"),r("Wiktionary","https://www.wiktionary.org/","进阶","项目平台","目标语言与资料核查能力","补充词源、例句或发音并记录可靠来源。"),r("Universal Dependencies","https://universaldependencies.org/","高级","项目平台","语言学、编程与语料分析","比较多语言句法标注或训练分析模型。")]),
 books:t("书单与资源","集中查看开放教材、语言课程和语料库。",[])
};
export const language:SubjectConfig={slug:"language",name:"语言",en:"LANGUAGE",intro:"语言学习既包括掌握一门语言，也包括理解人类语言如何形成结构、传递意义并随社会变化。",caution:"不要把收藏单词或观看内容当作掌握。稳定输入必须和主动回忆、真实输出、纠错与复习结合；语言及方言之间不存在科学意义上的高低优劣。",groups:[start,["基础",[["tools","学习工具"],["methods","语言学习方法"],["linguistics","语言学"]]],["结构与社会",[["sound","语音、语法与意义"],["society","社会语言学与语言变化"],["computational","计算语言学"]]],["语言路径",[["chinese","汉语"],["english","英语"],["projects","项目与进阶方向"],["books","书单与资源"]]]],topics,phases:[{time:"2–4 周",title:"确定目标与建立习惯",goal:"明确使用场景和可持续节奏。",learn:"发音系统、高频表达、间隔复习、输入和输出记录。",done:"连续四周完成每日短练习。",link:"methods"},{time:"3–6 个月",title:"建立基础交流能力",goal:"优先理解和表达高频意义。",learn:"核心词汇、基础语法、听读输入和短口语写作。",done:"能完成日常对话并理解分级材料。",link:"chinese"},{time:"3–6 个月",title:"扩展真实输入与输出",goal:"从教材过渡到真实语料。",learn:"新闻、播客、长文、讨论、写作和反馈。",done:"完成一篇反复修订的文章或一次主题演讲。",link:"english"},{time:"3–5 个月",title:"学习语言学框架",goal:"科学分析语言而不只凭语感。",learn:"语音、音系、形态、句法、语义、习得与变化。",done:"完成一次语料或声音分析。",link:"linguistics"},{time:"持续",title:"进入研究或技术应用",goal:"选择社会语言学、教学、翻译或 NLP。",learn:"语料、统计、田野、计算和研究伦理。",done:"公开一个带数据、方法和反思的语言项目。",link:"projects"}],tools:[["记忆与词典",[["Anki","https://apps.ankiweb.net/","间隔复习词汇和例句"],["Wiktionary","https://www.wiktionary.org/","查找释义、词源和发音"],["YouGlish","https://youglish.com/","在真实视频中检索发音与用法"]]],["语音与语料",[["Praat","https://www.fon.hum.uva.nl/praat/","分析语音"],["SKELL","https://www.sketchengine.eu/skell/","观察搭配和真实语料"],["WALS","https://wals.info/","比较世界语言结构"]]],["写作与研究",[["LanguageTool","https://languagetool.org/","检查和修订多语言文本"],["Zotero","https://www.zotero.org/","管理语言学文献"],["Python + NLTK","https://www.nltk.org/","处理文本语料"]]]],books:[["Essentials of Linguistics 2e","https://opentextbc.ca/essentialsoflinguistics2/","语言学 · 入门","带视频与练习的开放教材。"],["Learning Chinese","https://ocw.mit.edu/courses/res-21g-003-learning-chinese-a-foundation-course-in-mandarin-spring-2011/","汉语 · 入门","MIT 完整教材与音频。"],["Speech and Language Processing","https://web.stanford.edu/~jurafsky/slp3/","计算语言学 · 高级","免费教材草稿。"]],portals:[["MIT","MIT OCW Global Languages","https://ocw.mit.edu/search/?d=Global%20Studies%20and%20Languages","多种语言的大学课程。"],["MIT","MIT OCW Linguistics","https://ocw.mit.edu/search/?d=Linguistics","语言学核心和高级课程。"],["Open Textbook BC","Essentials of Linguistics","https://opentextbc.ca/essentialsoflinguistics2/","完整开放语言学教材。"]]};
