import {r,type SubjectConfig,type Topic} from "./subjectTypes";
const t=(title:string,intro:string,resources:ReturnType<typeof r>[]):Topic=>({title,intro,resources});
const start=["开始之前",[["intro","本站目的"],["how","如何使用本站"],["plan","学习规划"]]] as const;
const topics:Record<string,Topic>={
 tools:t("学习工具","获取合法文本、建立阅读批注、管理版本、引用和写作。",[]),
 reading:t("细读与文学写作","从语言、形式、叙述、意象和语境提出可由文本支持的解释。",[r("Writing About Literature","https://open.umn.edu/opentextbooks/textbooks/364","入门","开放教材","无需前置","学习细读、论点、证据和文学论文写作。"),r("MIT Reading Fiction","https://ocw.mit.edu/search/?q=reading%20fiction","进阶","公开课","基础阅读与写作","通过小说练习叙述视角、结构和形式分析。"),r("Yale Modern Poetry","https://oyc.yale.edu/english/engl-310","高级","公开课","诗歌细读与文学史基础","用完整大学课程深化韵律、声音和现代主义语境。")]),
 theory:t("文学理论","比较形式主义、结构主义、解释学、精神分析、马克思主义、女性主义和后殖民理论。",[r("Purdue OWL Literary Theory","https://owl.purdue.edu/owl/subject_specific_writing/writing_in_literature/literary_theory_and_schools_of_criticism/index.html","入门","公开讲义","细读基础","简明了解主要批评路径及提问方式。"),r("Yale ENGL 300 Introduction to Theory of Literature","https://oyc.yale.edu/english/engl-300","进阶","公开课","文学阅读与基础哲学","系统梳理二十世纪文学理论。"),r("Stanford Encyclopedia: Philosophy of Literature","https://plato.stanford.edu/entries/philosophy-literature/","高级","公开讲义","文学理论与哲学阅读","从权威综述和参考文献进入美学与解释问题。")]),
 chinese:t("中国文学","沿体裁、时代与思想语境阅读诗歌、散文、小说和戏剧。",[r("Chinese Text Project","https://ctext.org/","入门","项目平台","现代汉语","免费检索先秦至古代典籍及部分译文。"),r("MIT Chinese Literature","https://ocw.mit.edu/search/?q=Chinese%20literature","进阶","公开课","中国史与文学细读","通过大学课程连接作品、体裁和历史语境。"),r("Harvard Chinese Humanities","https://pll.harvard.edu/subject/china","高级","公开课","中国文学史与文言阅读","从诗学、思想和艺术传统开展专题研究。")]),
 world:t("世界文学","跨区域、体裁和时代阅读作品，避免把世界文学等同于单一传统。",[r("World Literature I: Beginnings to 1650","https://open.umn.edu/opentextbooks/textbooks/409","入门","开放教材","无需前置","经同行评审的开放选集，含导读和问题。"),r("MIT Foundations of World Culture II","https://ocw.mit.edu/courses/21l-002x-foundations-of-world-culture-ii-world-literatures-and-texts-spring-2012/","进阶","公开课","细读与世界史概览","从早期现代到近现代比较重要文本。"),r("MIT World Literatures","https://ocw.mit.edu/search/?q=world%20literatures","高级","公开课","文学理论与比较阅读","按旅行、殖民、翻译和全球流动深化专题。")]),
 comparative:t("比较文学与翻译","研究文本跨语言、媒介和文化传播时发生的变化。",[r("Compact Anthology of World Literature","https://open.umn.edu/opentextbooks/textbooks/410","入门","开放教材","世界文学概览","用跨文化选集练习共同主题比较。"),r("MIT Literature and Translation","https://ocw.mit.edu/search/?q=literature%20translation","进阶","公开课","至少一门外语更佳","研究翻译选择、不可译性和文本流通。"),r("Harvard World Literature","https://pll.harvard.edu/subject/literature","高级","公开课","比较文学与理论","从全球传播、经典形成和阅读制度深化研究。")]),
 modern:t("现代与当代文学","理解现代主义、殖民经验、身份、媒介与全球化如何改变文学。",[r("Compact Anthology of World Literature II","https://open.umn.edu/opentextbooks/textbooks/1236","入门","开放教材","世界文学概览","开放选集覆盖十七世纪至当代。"),r("Yale American Novel Since 1945","https://oyc.yale.edu/english/engl-291","进阶","公开课","小说细读与现代史","通过完整课程研究战后小说和阅读方法。"),r("MIT Contemporary Literature","https://ocw.mit.edu/search/?q=contemporary%20literature","高级","公开课","文学理论与现代史","按后殖民、技术、生态和身份进入专题。")]),
 digital:t("数字人文与文学研究","用文本分析、版本、地图和网络方法辅助解释，而非取代细读。",[r("The Programming Historian","https://programminghistorian.org/","入门","公开讲义","基础数字工具","逐步学习文本清理、分析和可视化。"),r("Voyant Tools","https://voyant-tools.org/","进阶","项目平台","文学研究与语料基础","探索词频、搭配和主题后回到文本验证。"),r("MIT Digital Humanities","https://digitalhumanities.mit.edu/","高级","项目平台","文学理论、数据与编程","理解数字方法、基础设施和批判性研究。")]),
 projects:t("项目与进阶方向","用细读论文、比较专题、数字展览或开放注释形成作品。",[r("Standard Ebooks","https://standardebooks.org/","入门","项目平台","基础文学阅读","选择公版作品做规范批注和版本比较。"),r("Project Gutenberg","https://www.gutenberg.org/","进阶","项目平台","文学史、引用与版本意识","围绕一个主题建立带出处的开放阅读单。"),r("MIT Digital Humanities Projects","https://digitalhumanities.mit.edu/","高级","项目平台","研究问题、文学理论和数字方法","设计一个可复现的语料或数字策展项目。")]),
 books:t("书单与资源","集中查看开放选集、大学课程和公版文本。",[])
};
export const literature:SubjectConfig={slug:"literature",name:"文学",en:"LITERATURE",intro:"文学研究通过细读、历史语境和理论比较，理解语言如何塑造经验、想象、身份与社会世界。",caution:"阅读量不等于研究能力。解释必须回到具体文本，并区分作品、译本、历史材料和自己的判断；使用公版资源时也要核对版本与译者。",groups:[start,["基础",[["tools","学习工具"],["reading","细读与文学写作"],["theory","文学理论"]]],["文学传统",[["chinese","中国文学"],["world","世界文学"],["modern","现代与当代文学"]]],["比较与实践",[["comparative","比较文学与翻译"],["digital","数字人文与文学研究"],["projects","项目与进阶方向"],["books","书单与资源"]]]],topics,phases:[{time:"1–2 个月",title:"建立细读习惯",goal:"从感想转向可验证的文本解释。",learn:"叙述、声音、意象、修辞、形式、批注和引用。",done:"完成一篇以文本证据为中心的短评。",link:"reading"},{time:"3–5 个月",title:"建立文学史地图",goal:"认识体裁、传统和时代变化。",learn:"诗歌、戏剧、小说；中国与世界文学代表作品。",done:"制作一条作品、历史与体裁相连的时间线。",link:"world"},{time:"2–4 个月",title:"学习理论工具",goal:"理解不同解释框架提出的问题。",learn:"形式、结构、性别、阶级、殖民、读者与历史。",done:"用两种理论比较同一文本并说明局限。",link:"theory"},{time:"2–4 个月",title:"进行跨文化比较",goal:"关注翻译、流通和权力关系。",learn:"比较文学、翻译、改编和世界文学。",done:"完成一篇跨语言或跨媒介比较文章。",link:"comparative"},{time:"持续",title:"形成独立研究作品",goal:"把问题、文本、语境和方法组织成论证。",learn:"文献、版本、数字工具、写作和修订。",done:"公开一篇论文、注释集或数字展览。",link:"projects"}],tools:[["阅读与文本",[["Standard Ebooks","https://standardebooks.org/","高质量公版电子书"],["Project Gutenberg","https://www.gutenberg.org/","检索公版作品"],["Internet Archive","https://archive.org/","查找历史版本和扫描本"]]],["批注与引用",[["Hypothesis","https://web.hypothes.is/","网页协作批注"],["Zotero","https://www.zotero.org/","管理作品、研究和引用"],["Obsidian","https://obsidian.md/","连接作品、概念和读书笔记"]]],["数字研究",[["Voyant Tools","https://voyant-tools.org/","文本探索与可视化"],["AntConc","https://www.laurenceanthony.net/software/antconc/","语料检索与搭配分析"],["The Programming Historian","https://programminghistorian.org/","学习数字人文方法"]]]],books:[["World Literature I","https://open.umn.edu/opentextbooks/textbooks/409","世界文学 · 入门","同行评审开放选集。"],["Compact Anthology of World Literature II","https://open.umn.edu/opentextbooks/textbooks/1236","现代文学 · 入门","覆盖十七世纪至当代。"],["Literature, the Humanities, and Humanity","https://open.umn.edu/opentextbooks/textbooks/204","细读 · 入门","开放文学导读。"]],portals:[["Yale","Open Yale Literature","https://oyc.yale.edu/courses","理论、诗歌、小说与经典作家课程。"],["MIT","MIT OCW Literature","https://ocw.mit.edu/search/?d=Literature","世界文学、比较文学和专题课程。"],["OEN","Open Textbook Library Literature","https://open.umn.edu/opentextbooks/subjects/literature-rhetoric-and-writing","开放选集和文学写作教材。"]]};
