import{createRoot}from"react-dom/client";
import PlatformHome from"./PlatformHome";
import KnowledgeGraphPlacement from"./KnowledgeGraphPlacement";
import Comments from"./Comments";
import FinanceHome from"./Home";
import TopicPage from"./TopicPage";
import BooksPage from"./BooksPage";
import MathHome from"./MathHome";
import MathTopicPage from"./MathTopicPage";
import MathBooksPage from"./MathBooksPage";
import{SubjectBooksPage,SubjectHome,SubjectTopicPage}from"./SubjectPages";
import{physics,computerScience}from"./subjectCatalog";
import{biology}from"./biologyCatalog";
import{psychology}from"./psychologyCatalog";
import{socialScience,history}from"./humanitiesCatalog";
import{chemistry,engineering}from"./newSubjectsCatalog";
import{language}from"./languageCatalog";
import{literature}from"./literatureCatalog";
import{preserveSidebarScroll}from"./sidebarScroll";
import{enableThemeInteraction}from"./themeInteraction";
import{enableAnalytics}from"./analytics";
import"./styles.css";import"./tools.css";import"./plan.css";import"./books.css";import"./mobile.css";import"./platform.css";import"./knowledge.css";import"./graph-interaction.css";import"./ollivere-theme.css";import"./comments.css";
import"./subject-menu.css";

const base=import.meta.env.BASE_URL.replace(/\/$/,"");
const path=location.pathname.replace(base,"");
const financeTopic=path.match(/^\/(?:finance\/)?topics\/([^/]+)/)?.[1];
const mathTopic=path.match(/^\/math\/topics\/([^/]+)/)?.[1];
const subjects=[physics,computerScience,biology,psychology,socialScience,history,chemistry,engineering,language,literature];
const subject=subjects.find(item=>path.match(new RegExp(`^/${item.slug}(?:/|$)`)));
const matchedSubjectTopic=subject?path.match(new RegExp(`^/${subject.slug}/topics/([^/]+)`))?.[1]:undefined;
const subjectTopic=subject?.slug==="literature"&&matchedSubjectTopic==="chinese"?"world":matchedSubjectTopic;
const genericPage=subject?(subjectTopic==="books"?<SubjectBooksPage subject={subject}/>:subjectTopic?<SubjectTopicPage subject={subject} topicSlug={subjectTopic}/>:<SubjectHome subject={subject}/>):null;
const page=genericPage??(mathTopic==="books"?<MathBooksPage/>:mathTopic?<MathTopicPage slug={mathTopic}/>:path.match(/^\/math\/?$/)?<MathHome/>:financeTopic==="books"?<BooksPage/>:financeTopic?<TopicPage slug={financeTopic}/>:path.match(/^\/finance\/?$/)?<FinanceHome/>:<><PlatformHome/><KnowledgeGraphPlacement/></>);
const discussionKey=subject?`${subject.slug}/${subjectTopic??"home"}`:mathTopic?`math/${mathTopic}`:path.match(/^\/math\/?$/)?"math/home":financeTopic?`finance/${financeTopic}`:path.match(/^\/finance\/?$/)?"finance/home":null;
createRoot(document.getElementById("root")!).render(<>{page}{discussionKey&&<div className="learning-comments"><Comments discussionKey={discussionKey}/></div>}</>);
preserveSidebarScroll();enableThemeInteraction();
enableAnalytics();
