/* eslint-disable no-irregular-whitespace -- full-width spacing is intentional in Chinese prose */
import {mathGroups} from "./mathData";
const b=import.meta.env.BASE_URL,u=(p:string)=>b+p.replace(/^\//,"");
const phases=[
 {n:"01",time:"2–6 周",title:"诊断并补齐基础",goal:"先确认算术、代数、函数和三角学哪里薄弱，不从最熟悉的内容重新刷起。",learn:"完成一次基础诊断；针对性复习分数、方程、不等式、函数图像、指数对数和三角函数；开始规范书写推导过程。",done:"能独立化简代数式、解常见方程，并从公式、图像和文字三种方式理解函数。",link:"foundations"},
 {n:"02",time:"1–2 个月",title:"学习证明与数学语言",goal:"尽早理解定义、命题和证明，避免只会套公式。",learn:"学习集合、逻辑、量词、反证法、归纳法、充分必要条件；每周完整写出至少两道证明题。",done:"能判断一个论证缺少哪一步，并用清楚的语言写出直接证明、反证和归纳证明。",link:"proofs"},
 {n:"03",time:"4–7 个月",title:"完成两门核心语言",goal:"先学单变量微积分与线性代数，再学习多变量微积分；计算与概念各占一半。",learn:"理解极限、导数、积分、级数；掌握向量、矩阵、线性映射、正交和特征值；配合几何图像与数值实验。",done:"能解释导数与积分的含义，解决基础优化问题，并用线性代数表达高维关系。",link:"calculus"},
 {n:"04",time:"3–5 个月",title:"进入不确定性与动态系统",goal:"用概率统计理解随机性，用微分方程理解随时间变化的系统。",learn:"学习随机变量、条件概率、期望、估计与检验；学习常微分方程、线性系统、稳定性和简单数值方法。",done:"能建立一个概率模型、解释统计结论，并为简单动态问题写出和分析微分方程。",link:"probability"},
 {n:"05",time:"4–8 个月",title:"建立严格理论基础",goal:"根据兴趣选择实分析、抽象代数或离散数学，不要求同时全部推进。",learn:"实分析强化极限与连续的严格性；抽象代数研究结构与对称；离散数学研究图、组合和算法相关结构。",done:"能持续阅读定义—定理—证明型教材，并独立完成一组中等难度证明题。",link:"real-analysis"},
 {n:"06",time:"持续进行",title:"用项目连接现实问题",goal:"把数学变成可检验的证明、模型、程序或研究报告。",learn:"选择优化、数值计算、数学建模、金融数学、机器学习或物理建模；记录假设、推导、实现、验证和局限。",done:"完成一个别人能够复现、检查和提出反例的数学作品，并根据反馈迭代。",link:"projects"}
];

export default function MathHome(){return <div className="shell"><MathHeader/><MathSide/><main><section id="intro" className="hero"><small>SELF-TAUGHT MATHEMATICS</small><h1>自学数学</h1><p>数学不是公式清单，而是一套描述结构、变化与不确定性的语言。这里从零基础出发，以定义、直觉、证明、计算和实践共同组织学习路径。</p><aside>不要用“看懂了”代替“会做了”。真正的理解需要你关掉答案，独立计算、证明、建模并解释每一步。</aside></section><section id="how"><h2>如何使用本站</h2><p>左侧目录按照知识依赖组织。先完成基础诊断，再为每个阶段选择一门主课；阅读定义和例题后必须做题，并定期用证明、代码或模型检验理解。</p><div className="legend" aria-label="资源类型图例"><div><i className="resource-mark course"/><span><b>公开课</b><small>绿色书签</small></span></div><div><i className="resource-mark paper"/><span><b>讲义与项目</b><small>红色书签</small></span></div><div><i className="resource-mark book"/><span><b>书籍与教材</b><small>蓝色书签</small></span></div></div></section><section id="plan"><h2>学习规划</h2><p className="plan-intro">这是一条面向零基础学习者的参考路径。每周稳定投入 6–10 小时，通常需要 18–30 个月建立本科核心基础；进度慢并不意味着没有天赋，数学理解本来就依赖反复尝试。</p><div className="beginner-note"><strong>开始前先建立四个习惯</strong><ul><li>每一章至少完成一组不看答案的习题，错误题比收藏新资源更重要。</li><li>遇到定义时自己写例子与反例，遇到定理时先问条件为什么不能删除。</li><li>计算卡住就拆成更小步骤；证明卡住就从结论倒推需要什么条件。</li><li>保留一份错题与问题日志，每周复盘，而不是追求一次性全部理解。</li></ul></div><div className="plan-steps">{phases.map(p=><article key={p.n}><div className="phase-meta"><span>{p.n}</span><small>建议用时<br/><b>{p.time}</b></small></div><div><h3>{p.title}</h3><p className="phase-goal">{p.goal}</p><dl><div><dt>主要学习内容</dt><dd>{p.learn}</dd></div><div><dt>完成标志</dt><dd>{p.done}</dd></div></dl><a href={u(`math/topics/${p.link}/`)}>进入相关章节 →</a></div></article>)}</div><div className="weekly"><h3>适合初学者的一周节奏</h3><p><b>2 小时课程</b>：理解新定义与例题　·　<b>3–4 小时练习</b>：独立计算和证明　·　<b>1 小时复盘</b>：整理错误与反例　·　<b>1–2 小时实验</b>：用图像、代码或现实问题验证概念。</p></div></section></main></div>}

export function MathHeader(){const toggle=(button?:HTMLButtonElement)=>{const open=document.body.classList.toggle("menu-open");button?.setAttribute("aria-expanded",String(open))};return <><header><button className="menu-button" aria-label="打开数学目录" aria-expanded="false" onClick={e=>toggle(e.currentTarget)}><span/><span/><span/></button><a href={`${b}math/`}><b>自学数学</b></a><nav><a href={b}>学科首页</a><a href="https://github.com/ming1024yue/finance-self-taught/issues" target="_blank" rel="noreferrer">反馈与共建</a></nav></header><button className="mobile-overlay" aria-label="关闭数学目录" onClick={()=>toggle()}/></>}
export function MathSide({active=""}:{active?:string}){return <aside className="sidebar"><nav>{mathGroups.map(([group,items])=><section key={group}><h3>{group}</h3>{items.map(([id,name])=><a className={id===active?"active":""} key={id} href={["intro","how","plan"].includes(id)?`${b}math/#${id}`:u(`math/topics/${id}/`)}>{name}</a>)}</section>)}</nav></aside>}
