const base=import.meta.env.BASE_URL;
const subjects=[
 {name:"金融",en:"FINANCE",status:"持续完善中",desc:"从会计、经济学和数学基础出发，学习公司金融、投资、资产定价，并通过研究项目形成能力。",href:`${base}finance/`,active:true},
 {name:"数学",en:"MATHEMATICS",status:"筹备中",desc:"建立从基础数学到高等数学、概率统计和应用数学的系统路径。"},
 {name:"计算机",en:"COMPUTER SCIENCE",status:"筹备中",desc:"从编程基础进入算法、系统、人工智能与软件工程。"},
 {name:"物理",en:"PHYSICS",status:"筹备中",desc:"从经典力学和电磁学出发，逐步进入现代物理与实验方法。"},
 {name:"工程",en:"ENGINEERING",status:"筹备中",desc:"连接数学、科学与设计，形成解决真实工程问题的能力。"}
];
export default function PlatformHome(){return <div className="platform"><header className="platform-header"><a href={base}><b>自学路径</b><small>SELF-TAUGHT PATHS</small></a><nav><a href="#subjects">学科</a><a href="#about">关于</a><a href="https://github.com/ming1024yue/finance-self-taught/issues" target="_blank" rel="noreferrer">反馈与共建</a></nav></header><main className="platform-main"><section className="platform-hero"><small>OPEN LEARNING PATHS</small><h1>为每一门学科，<br/>整理一条真正可走的自学路径。</h1><p>本站希望减少优质教育资源与学习者之间的信息差。我们按照知识依赖关系，整理公开课、教材、论文、工具与实践项目，帮助零基础学习者逐步建立完整的知识体系。</p></section><section id="subjects"><div className="platform-heading"><small>SUBJECTS</small><h2>选择学科</h2><p>目前优先完善金融学科，其余学科将在形成可靠内容框架后陆续开放。</p></div><div className="subject-grid">{subjects.map((s,i)=>s.active?<a className="subject-card active" href={s.href} key={s.name}><span className="subject-num">0{i+1}</span><small>{s.en}</small><h3>{s.name}</h3><p>{s.desc}</p><footer><b>{s.status}</b><span>进入学科 →</span></footer></a>:<article className="subject-card" key={s.name}><span className="subject-num">0{i+1}</span><small>{s.en}</small><h3>{s.name}</h3><p>{s.desc}</p><footer><b>{s.status}</b></footer></article>)}</div></section><section id="about" className="platform-about"><h2>我们如何整理内容</h2><div><p><b>路径优先</b><br/>先说明学习顺序与前置要求，再推荐资源。</p><p><b>公开可得</b><br/>优先选择大学公开课、开放教材和原始资料。</p><p><b>能够实践</b><br/>不止于观看课程，最终要形成习题、报告、代码或项目。</p></div></section></main></div>}
