import {r,type SubjectConfig,type Topic} from "./subjectTypes";
const t=(title:string,intro:string,resources:ReturnType<typeof r>[]):Topic=>({title,intro,resources});
const start=["开始之前",[["intro","本站目的"],["how","如何使用本站"],["plan","学习规划"]]] as const;
const topics:Record<string,Topic>={
 tools:t("学习工具","用文献、实验和统计工具区分直觉、证据与可复现结论。",[]),
 methods:t("研究方法与统计","学习实验、观察、测量、因果推断和开放科学。",[r("Open Textbook: Research Methods in Psychology","https://opentextbc.ca/researchmethods/","入门","开放教材","无需前置","从问题、测量和实验设计进入心理学研究。"),r("OpenStax Introductory Statistics","https://openstax.org/details/books/introductory-statistics-2e","进阶","开放教材","高中代数","补齐描述统计、推断和回归。"),r("Improving Your Statistical Inferences","https://lakens.github.io/statistical_inferences/","高级","开放教材","基础统计","深入功效、效应量、误差控制和透明分析。")]),
 introduction:t("心理学导论","建立感觉、学习、记忆、发展、社会和临床的学科地图。",[r("OpenStax Psychology 2e","https://openstax.org/details/books/psychology-2e","入门","开放教材","无需前置","免费完整导论教材，章节结构清晰。"),r("Yale PSYC 110 Introduction to Psychology","https://oyc.yale.edu/introduction-psychology/psyc-110","进阶","公开课","无需前置","从知觉、发展、社会和异常心理建立经典框架。"),r("MIT 9.00SC Introduction to Psychology","https://ocw.mit.edu/courses/9-00sc-introduction-to-psychology-fall-2011/","高级","公开课","基础生物与统计更佳","自学型课程，强调科学证据与神经基础。")]),
 biological:t("生物心理学与神经科学","理解神经元、脑系统、激素和行为之间的联系。",[r("OpenStax Psychology 2e: Biopsychology","https://openstax.org/books/psychology-2e/pages/3-introduction","入门","开放教材","普通生物基础","用概览章节建立脑与行为语言。"),r("MIT Introduction to Neuroscience","https://ocw.mit.edu/search/?q=introduction%20neuroscience","进阶","公开课","生物、化学与心理学导论","从神经信号进入感觉、运动和学习。"),r("Neuroscience — NCBI Bookshelf","https://www.ncbi.nlm.nih.gov/books/NBK10799/","高级","开放教材","细胞生物学与生理学","深入神经系统的结构、功能和实验依据。")]),
 cognitive:t("认知心理学","研究注意、知觉、记忆、语言、推理和决策。",[r("Noba: Cognition","https://nobaproject.com/browse-content","入门","开放教材","心理学导论","免费模块化阅读，适合按概念补充。"),r("MIT Cognitive Science","https://ocw.mit.edu/search/?q=cognitive%20science","进阶","公开课","心理学导论与统计","连接心理学、神经科学、语言和计算模型。"),r("Computational Cognitive Science","https://ocw.mit.edu/search/?q=computational%20cognitive%20science","高级","公开课","概率、编程与认知心理学","用概率模型解释学习、推理和决策。")]),
 development:t("发展心理学","研究认知、情绪与社会能力如何在生命历程中变化。",[r("OpenStax Lifespan Development","https://openstax.org/details/books/lifespan-development","入门","开放教材","无需前置","覆盖从孕期到老年的发展。"),r("MIT Developmental Psychology","https://ocw.mit.edu/search/?q=developmental%20psychology","进阶","公开课","心理学导论与研究方法","从实验研究理解儿童认知和社会发展。"),r("Noba: Development","https://nobaproject.com/browse-content","高级","开放教材","研究方法与统计","选择专题比较理论、测量和证据。")]),
 social:t("社会与人格心理学","研究情境、群体、自我和稳定差异如何影响行为。",[r("OpenStax Psychology 2e: Social Psychology","https://openstax.org/books/psychology-2e/pages/12-introduction","入门","开放教材","心理学导论","介绍归因、态度、群体和人际关系。"),r("Noba: Social Psychology","https://nobaproject.com/browse-content","进阶","开放教材","研究方法","以短模块连接经典理论和现代研究。"),r("MIT Social Psychology","https://ocw.mit.edu/search/?q=social%20psychology","高级","公开课","统计与实验设计","进一步分析社会认知、文化和群体过程。")]),
 clinical:t("异常与临床心理学","理解诊断、风险因素、评估和循证干预，同时认识其边界。",[r("OpenStax Psychology 2e: Disorders","https://openstax.org/books/psychology-2e/pages/15-introduction","入门","开放教材","心理学导论","概览障碍分类、成因和治疗。"),r("Noba: Clinical Psychology","https://nobaproject.com/browse-content","进阶","开放教材","研究方法与统计","从证据角度理解评估和干预。"),r("MIT Mental Health Courses","https://ocw.mit.edu/search/?q=mental%20health","高级","公开课","生物、发展与社会心理学","从跨学科课程理解心理健康研究；不替代专业诊疗。")]),
 projects:t("项目与进阶方向","通过复现、问卷或行为实验练习透明、合乎伦理的研究。",[r("PsyToolkit","https://www.psytoolkit.org/","入门","项目平台","研究方法","在线搭建简单实验或问卷并分析结果。"),r("Open Science Framework","https://osf.io/","进阶","项目平台","统计与研究设计","预注册、管理材料和分享可复现项目。"),r("Many Labs Projects","https://osf.io/ct89g/","高级","项目平台","统计、实验和文献阅读","阅读大规模复现项目并尝试复现一个效应。")]),
 books:t("书单与资源","集中查看开放教材和大学公开课程。",[])
};
export const psychology:SubjectConfig={slug:"psychology",name:"心理学",en:"PSYCHOLOGY",intro:"心理学以可检验的方法研究心智与行为，从大脑和认知延伸到发展、人格、群体与心理健康。",caution:"心理学不是凭感觉分析他人。区分相关与因果，关注样本、测量、效应量和复现；临床内容不能替代专业诊断与治疗。",groups:[start,["基础",[["tools","学习工具"],["methods","研究方法与统计"],["introduction","心理学导论"]]],["核心",[["biological","生物心理学与神经科学"],["cognitive","认知心理学"],["development","发展心理学"],["social","社会与人格心理学"],["clinical","异常与临床心理学"]]],["研究与实践",[["projects","项目与进阶方向"],["books","书单与资源"]]]],topics,phases:[{time:"1–2 个月",title:"先建立科学研究观",goal:"能分辨描述、相关和因果结论。",learn:"变量、测量、实验、抽样、伦理和基础统计。",done:"能批判性阅读一则心理学研究报道。",link:"methods"},{time:"2–3 个月",title:"完成心理学导论",goal:"建立主要分支和关键问题的地图。",learn:"脑、感觉、学习、记忆、发展、社会与临床。",done:"用概念图解释各分支如何连接。",link:"introduction"},{time:"3–5 个月",title:"深化认知与生物基础",goal:"把行为现象连接到信息加工和神经机制。",learn:"注意、记忆、语言、决策、神经系统。",done:"能比较行为、神经与计算三种解释层次。",link:"cognitive"},{time:"2–4 个月",title:"理解个体与社会情境",goal:"理解发展轨迹、人格差异和群体影响。",learn:"发展、人格、社会认知、文化和心理健康。",done:"能用证据讨论一个现实行为问题。",link:"social"},{time:"持续",title:"做透明且合乎伦理的研究",goal:"把问题变成可复现的小型项目。",learn:"预注册、量表、实验、分析、限制和开放材料。",done:"发布一份匿名、可复查的研究报告。",link:"projects"}],tools:[["文献",[["APA PsycNet","https://psycnet.apa.org/","检索心理学论文与摘要"],["PubMed","https://pubmed.ncbi.nlm.nih.gov/","检索神经与临床研究"],["Zotero","https://www.zotero.org/","管理文献和引用"]]],["实验与问卷",[["PsyToolkit","https://www.psytoolkit.org/","在线创建行为实验和问卷"],["jsPsych","https://www.jspsych.org/","用 JavaScript 构建浏览器实验"],["Qualtrics","https://www.qualtrics.com/","设计和分发问卷"]]],["开放科学与分析",[["OSF","https://osf.io/","预注册并公开研究材料"],["JASP","https://jasp-stats.org/","图形化统计分析"],["R","https://www.r-project.org/","可复现统计和可视化"]]]],books:[["OpenStax Psychology 2e","https://openstax.org/details/books/psychology-2e","导论 · 入门","完整免费教材。"],["Research Methods in Psychology","https://opentextbc.ca/researchmethods/","方法 · 入门","从问题到报告的开放教材。"],["Improving Your Statistical Inferences","https://lakens.github.io/statistical_inferences/","统计 · 进阶","强化研究推断和开放科学。"]],portals:[["Yale","Open Yale Psychology","https://oyc.yale.edu/psychology","完整导论课程。"],["MIT","MIT OCW Brain and Cognitive Sciences","https://ocw.mit.edu/search/?d=Brain%20and%20Cognitive%20Sciences","认知、神经和计算方向课程。"],["Noba","Noba Project","https://nobaproject.com/","由学者编写的免费心理学模块。"]]};
