import type {SubjectConfig} from "./subjectTypes";
const b=import.meta.env.BASE_URL,u=(p:string)=>b+p.replace(/^\//,"");
const mark=(kind:string)=>kind.includes("教材")?"book":kind.includes("讲义")||kind.includes("项目")?"paper":"course";

export function SubjectHeader({subject}:{subject:SubjectConfig}){const toggle=(button?:HTMLButtonElement)=>{const open=document.body.classList.toggle("menu-open");button?.setAttribute("aria-expanded",String(open))};return <><header><button className="menu-button" aria-label={`打开${subject.name}目录`} aria-expanded="false" onClick={e=>toggle(e.currentTarget)}><span/><span/><span/></button><a href={u(`${subject.slug}/`)}><b>自学{subject.name}</b></a><a className="mobile-home" href={b} aria-label="返回网站总首页">总首页</a><nav><a href={b}>学科首页</a><a href="https://github.com/ming1024yue/finance-self-taught/issues" target="_blank" rel="noreferrer">反馈与共建</a></nav></header><button className="mobile-overlay" aria-label="关闭学习目录" onClick={()=>toggle()}/></>}
export function SubjectSide({subject,active=""}:{subject:SubjectConfig;active?:string}){return <aside className="sidebar"><nav>{subject.groups.map(([group,items])=><section key={group}><h3>{group}</h3>{items.map(([id,name])=><a className={id===active?"active":""} key={id} href={["intro","how","plan"].includes(id)?u(`${subject.slug}/#${id}`):u(`${subject.slug}/topics/${id}/`)}>{name}</a>)}</section>)}</nav></aside>}
export function SubjectHome({subject}:{subject:SubjectConfig}){return <div className="shell"><SubjectHeader subject={subject}/><SubjectSide subject={subject}/><main><section id="intro" className="hero"><small>SELF-TAUGHT {subject.en}</small><h1>自学{subject.name}</h1><p>{subject.intro}</p><aside>{subject.caution}</aside></section><section id="how"><h2>如何使用本站</h2><p>左侧目录按照知识依赖组织。每个阶段只选择一套主资源，先理解概念与方法，再通过练习、写作、实验或项目检验学习成果。</p><div className="legend"><div><i className="resource-mark course"/><span><b>公开课</b><small>绿色书签</small></span></div><div><i className="resource-mark paper"/><span><b>讲义与项目</b><small>红色书签</small></span></div><div><i className="resource-mark book"/><span><b>书籍与教材</b><small>蓝色书签</small></span></div></div></section><section id="plan"><h2>学习规划</h2><p className="plan-intro">以下路线面向零基础学习者。建议每周稳定投入 6–10 小时，并把至少一半时间用于主动练习、复述、分析和项目。</p><div className="beginner-note"><strong>判断自己是否真正学会</strong><ul><li>能不用原文，用自己的语言解释核心概念。</li><li>能独立完成习题、分析材料或小型项目。</li><li>能指出方法的假设、证据来源与适用边界。</li></ul></div><div className="plan-steps">{subject.phases.map((p,index)=><article key={p.title}><div className="phase-meta"><span>{String(index+1).padStart(2,"0")}</span><small>建议用时<br/><b>{p.time}</b></small></div><div><h3>{p.title}</h3><p className="phase-goal">{p.goal}</p><dl><div><dt>主要学习内容</dt><dd>{p.learn}</dd></div><div><dt>完成标志</dt><dd>{p.done}</dd></div></dl><a href={u(`${subject.slug}/topics/${p.link}/`)}>进入相关章节 →</a></div></article>)}</div></section></main></div>}
export function SubjectTopicPage({subject,topicSlug}:{subject:SubjectConfig;topicSlug:string}){const topic=subject.topics[topicSlug];if(!topic)return <main><h1>页面不存在</h1></main>;return <div className="shell"><SubjectHeader subject={subject}/><SubjectSide subject={subject} active={topicSlug}/><main><section className="hero"><small>SELF-TAUGHT {subject.en} / {topic.title}</small><h1>{topic.title}</h1><p>{topic.intro}</p></section>{topicSlug==="tools"?<div className="tool-sections">{subject.tools.map(([title,items])=><section key={title}><h2>{title}</h2><div className="tool-list">{items.map(([name,url,note])=><p key={name}><a href={url} target="_blank" rel="noreferrer">{name}</a><span>：{note}</span></p>)}</div></section>)}</div>:<section><h2>分级精选资源</h2><div className="cards">{topic.resources.map(x=><article className="card" key={x.name}><i className={`resource-mark ${mark(x.kind)}`}/><div><small>{x.kind} · {x.level}</small><h3><a href={x.url} target="_blank" rel="noreferrer">{x.name}</a></h3><p>{x.description}</p><dl><div><dt>难度</dt><dd>{x.level}</dd></div><div><dt>前置要求</dt><dd>{x.pre}</dd></div></dl></div></article>)}</div></section>}</main></div>}
export function SubjectBooksPage({subject}:{subject:SubjectConfig}){return <div className="shell"><SubjectHeader subject={subject}/><SubjectSide subject={subject} active="books"/><main><section className="hero"><small>SELF-TAUGHT {subject.en} / 书单与资源</small><h1>书单与资源</h1><p>优先收录可以合法免费阅读的教材、原始资料和大学官方公开课程。先选一套主资源，再用其他材料补充视角。</p></section><section><h2>公开电子书</h2><div className="library-list">{subject.books.map(([name,url,tag,text])=><article key={name}><i className="resource-mark book"/><div><small>{tag}</small><h3><a href={url} target="_blank" rel="noreferrer">{name} ↗</a></h3><p>{text}</p></div></article>)}</div></section><section><h2>公开课程与资料入口</h2><div className="course-portals">{subject.portals.map(([tag,name,url,text])=><article key={name}><span>{tag}</span><h3><a href={url} target="_blank" rel="noreferrer">{name} ↗</a></h3><p>{text}</p></article>)}</div></section></main></div>}
