import {r,type SubjectConfig,type Topic} from "./subjectTypes";
const t=(title:string,intro:string,resources:ReturnType<typeof r>[]):Topic=>({title,intro,resources});
const starts=[["开始之前",[["intro","本站目的"],["how","如何使用本站"],["plan","学习规划"]]]] as const;
const commonTools=[["记录与写作",[["Obsidian","https://obsidian.md/","建立概念、问题与资料之间的连接"],["Zotero","https://www.zotero.org/","管理教材、论文和引用"],["Overleaf","https://www.overleaf.com/","撰写带公式、图表和引用的报告"]]],["数据与计算",[["Python","https://www.python.org/","数据处理、模拟与可复现分析"],["Jupyter","https://jupyter.org/","整合代码、图表与文字说明"],["GitHub","https://github.com/","保存和分享项目版本"]]]] as const;
const physicsTopics:Record<string,Topic>={
 tools:t("学习工具","用仿真、计算和实验记录连接方程与真实现象。",[]),
 foundations:t("数学与物理基础","补齐单位、向量、函数和微积分，并建立量纲分析习惯。",[
  r("OpenStax College Physics 2e","https://openstax.org/details/books/college-physics-2e","入门","开放教材","高中代数","以代数为主的完整入门教材，适合先建立概念与问题求解方法。"),r("MIT Introductory Science and Math","https://ocw.mit.edu/collections/introductory-science-and-math/","进阶","公开课","代数与三角学","MIT 整理的微积分、力学、电磁学起点与自学顺序。"),r("OpenStax University Physics Volume 1","https://openstax.org/details/books/university-physics-volume-1","高级","开放教材","单变量微积分","以微积分表达大学物理，为核心课程提供统一参考。")]),
 mechanics:t("经典力学","从运动学、牛顿定律与守恒律进入拉格朗日和哈密顿方法。",[
  r("MIT 8.01SC Classical Mechanics","https://ocw.mit.edu/courses/8-01sc-classical-mechanics-fall-2016/","入门","公开课","代数、向量；可同步学习微积分","自学型课程，含短视频、在线教材、例题和完整问题集。"),r("OpenStax University Physics Volume 1","https://openstax.org/details/books/university-physics-volume-1","进阶","开放教材","单变量微积分","系统覆盖质点、刚体、引力、振动与流体。"),r("MIT 8.09 Classical Mechanics III","https://ocw.mit.edu/courses/8-09-classical-mechanics-iii-fall-2014/","高级","公开课","微积分、线性代数与微分方程","进入变分原理、哈密顿力学、刚体、混沌与连续介质。")]),
 electromagnetism:t("电磁学","理解电场、磁场、电势、电路和 Maxwell 方程。",[
  r("OpenStax University Physics Volume 2","https://openstax.org/details/books/university-physics-volume-2","入门","开放教材","力学与微积分","从静电、电路进入磁场、电磁感应和电磁波。"),r("MIT 8.02 Physics II: Electricity and Magnetism","https://ocw.mit.edu/courses/8-02-physics-ii-electricity-and-magnetism-spring-2019/","进阶","公开课","力学与多变量微积分","MITx 系列课程，围绕静电、磁场与 Maxwell 方程组织视频。"),r("MIT 8.07 Electromagnetism II","https://ocw.mit.edu/courses/8-07-electromagnetism-ii-fall-2012/","高级","公开课","矢量分析、微分方程与基础电磁学","深入边值问题、电磁辐射、相对论表述与介质。")]),
 waves:t("振动、波与光学","用叠加、傅里叶分析和波动方程理解声、光与量子波。",[
  r("MIT 8.03SC Physics III: Vibrations and Waves","https://ocw.mit.edu/courses/8-03sc-physics-iii-vibrations-and-waves-fall-2016/","入门","公开课","力学与微积分","覆盖简谐振动、耦合振子、波动、干涉、衍射与偏振。"),r("OpenStax University Physics Volume 1–3","https://openstax.org/details/books/university-physics-volume-1","进阶","开放教材","微积分与力学","结合力学、电磁学和现代物理章节建立波的统一认识。"),r("MIT 8.311 Electromagnetic Theory","https://ocw.mit.edu/courses/8-311-electromagnetic-theory-spring-2004/","高级","公开课","电磁学与数学物理","从场方程深入波导、辐射与相对论电动力学。")]),
 thermo:t("热力学与统计物理","从宏观状态量进入熵、系综和微观统计解释。",[
  r("OpenStax University Physics Volume 2: Thermodynamics","https://openstax.org/books/university-physics-volume-2/pages/1-introduction","入门","开放教材","力学与微积分","介绍温度、热、热力学定律、熵和热机。"),r("MIT 8.044 Statistical Physics I","https://ocw.mit.edu/courses/8-044-statistical-physics-i-spring-2013/","进阶","公开课","概率、微积分与基础力学","把热力学与概率统计连接到微观粒子模型。"),r("MIT 8.333 Statistical Mechanics I","https://ocw.mit.edu/courses/8-333-statistical-mechanics-i-statistical-mechanics-of-particles-fall-2013/","高级","公开课","量子、概率与多变量微积分","研究系综、量子统计、相变和相互作用粒子。")]),
 relativity:t("相对论","理解时空、Lorentz 变换、等效原理和引力几何。",[
  r("Spacetime Physics — Taylor & Wheeler","https://www.eftaylor.com/spacetimephysics/","入门","开放教材","代数与基础力学","作者公开提供的相对论教材，以事件和时空间隔建立直觉。"),r("MIT 8.20 Introduction to Special Relativity","https://ocw.mit.edu/courses/8-20-introduction-to-special-relativity-january-iap-2021/","进阶","公开课","力学、微积分与线性代数","集中学习 Lorentz 变换、相对论动力学和电磁联系。"),r("MIT 8.962 General Relativity","https://ocw.mit.edu/courses/8-962-general-relativity-spring-2020/","高级","公开课","张量分析、微分几何与经典场论","进入 Einstein 方程、黑洞、引力波和宇宙学。")]),
 quantum:t("量子力学","学习态、算符、测量、波函数和量子动力学。",[
  r("MIT 8.04 Quantum Physics I","https://ocw.mit.edu/courses/8-04-quantum-physics-i-spring-2016/","入门","公开课","波动、微积分、线性代数与微分方程","从实验事实进入波函数、Schrödinger 方程与一维体系。"),r("MIT 8.05 Quantum Physics II","https://ocw.mit.edu/courses/8-05-quantum-physics-ii-fall-2013/","进阶","公开课","量子 I 与线性代数","覆盖形式体系、角动量、自旋、三维体系与近似方法。"),r("MIT 8.06 Quantum Physics III","https://ocw.mit.edu/courses/8-06-quantum-physics-iii-spring-2018/","高级","公开课","量子 II、电磁学与统计物理","深入微扰、散射、相同粒子和相对论量子理论起点。")]),
 experiment:t("实验与计算物理","学习测量、不确定度、数据拟合、仿真和实验报告。",[
  r("Open Source Physics","https://www.compadre.org/osp/","入门","项目平台","基础物理","使用开放仿真观察模型、改变参数并与预测比较。"),r("MIT 8.13 Experimental Physics I","https://ocw.mit.edu/courses/8-13-14-experimental-physics-i-ii-junior-lab-fall-2016-spring-2017/","进阶","公开课","核心物理、统计与编程","通过实验设计、误差分析和技术写作形成研究能力。"),r("Computational Physics — Mark Newman","https://public.websites.umich.edu/~mejn/cp/","高级","公开讲义","Python、微积分与线性代数","作者提供程序与资料，练习数值积分、ODE、Monte Carlo 和 PDE。")]),
 projects:t("项目与进阶方向","通过可复现实验或计算项目进入天体、凝聚态、粒子与复杂系统。",[
  r("PhET Physics Simulations","https://phet.colorado.edu/en/simulations/filter?subjects=physics&type=html","入门","项目平台","基础物理","选择一个仿真提出可测问题，记录变量、预测和结果。"),r("MIT OpenCourseWare Physics","https://ocw.mit.edu/search/?d=Physics","进阶","项目平台","完成大学物理核心","按兴趣查找天体、核物理、凝聚态、粒子与生物物理课程。"),r("CERN Open Data","https://opendata.cern.ch/","高级","项目平台","统计、编程与现代物理","使用真实粒子物理数据完成分析并记录选择条件与不确定度。")]),books:t("书单与资源","集中查看开放教材与大学官方课程入口。",[])
};

export const physics:SubjectConfig={slug:"physics",name:"物理",en:"PHYSICS",intro:"物理用实验、数学和模型寻找自然界可检验的规律。这条路径从力学出发，逐步连接电磁、热、波、相对论和量子世界。",caution:"不要把物理学成公式匹配。先画图、说明假设和守恒关系，再计算，并始终检查单位、数量级与实验意义。",groups:[...starts,["基础",[["tools","学习工具"],["foundations","数学与物理基础"]]],["大学核心",[["mechanics","经典力学"],["electromagnetism","电磁学"],["waves","振动、波与光学"],["thermo","热力学与统计物理"]]],["现代物理",[["relativity","相对论"],["quantum","量子力学"]]],["研究与实践",[["experiment","实验与计算物理"],["projects","项目与进阶方向"],["books","书单与资源"]]]],topics:physicsTopics,phases:[{time:"1–2 个月",title:"补齐数学与测量基础",goal:"建立单位、向量、函数和实验误差意识。",learn:"代数、三角、向量、微积分直觉、量纲分析与数据图像。",done:"能把文字问题画成受力图并检查结果单位。",link:"foundations"},{time:"4–6 个月",title:"完成经典物理核心",goal:"用力学、电磁学和波建立统一的问题求解框架。",learn:"运动、守恒、场、电路、振动、波与光。",done:"独立完成核心习题并解释推导的物理含义。",link:"mechanics"},{time:"3–5 个月",title:"理解热与随机性",goal:"连接宏观定律和微观统计。",learn:"热力学定律、熵、分布、系综与相变直觉。",done:"能分析简单热过程并解释熵的统计意义。",link:"thermo"},{time:"4–8 个月",title:"进入现代物理",goal:"接受经典直觉的边界并学习新的数学结构。",learn:"狭义相对论、波函数、算符、自旋与量子动力学。",done:"解决一维量子与相对论运动学问题。",link:"quantum"},{time:"持续",title:"通过实验和计算形成能力",goal:"用数据和可复现模型检验理论。",learn:"误差分析、拟合、仿真、实验设计与研究写作。",done:"完成可复现的实验或计算报告。",link:"projects"}],tools:[...commonTools,["物理专用",[["PhET","https://phet.colorado.edu/","交互探索力学、电磁、波与量子现象"],["Tracker","https://opensourcephysics.github.io/tracker-website/index.html","从视频提取运动数据并建模"],["Open Source Physics","https://www.compadre.org/osp/","开放仿真、模型和教学资源"]]]],books:[["OpenStax University Physics","https://openstax.org/details/books/university-physics-volume-1","大学物理 · 入门","三卷开放教材，覆盖经典与现代物理。"],["Spacetime Physics","https://www.eftaylor.com/spacetimephysics/","相对论 · 进阶","作者公开提供的狭义相对论教材。"],["Computational Physics","https://public.websites.umich.edu/~mejn/cp/","计算物理 · 进阶","配套 Python 程序和练习。"]],portals:[["清华","清华大学：大学物理 1","https://www.xuetangx.com/course/THU07021000288/5883457","面向工科低年级，系统覆盖力学与热学。"],["MIT","MIT OCW Physics","https://ocw.mit.edu/search/?d=Physics","覆盖本科核心和多个研究方向。"],["OpenStax","Open Physics Textbooks","https://openstax.org/subjects/science","合法免费阅读的大学物理教材。"],["Colorado","PhET Simulations","https://phet.colorado.edu/en/simulations/filter?subjects=physics&type=html","用于概念探索和小型实验。"]]};

const csTopics:Record<string,Topic>={
 tools:t("学习工具","建立编辑、调试、版本管理与实验环境。",[]),
 programming:t("编程基础","学习把问题拆成精确步骤，并用程序表达、测试和改进。",[r("CS50x Introduction to Computer Science","https://cs50.harvard.edu/x/","入门","公开课","无需前置","Harvard 的完整入门课，从 C、Python、SQL 和 Web 建立计算思维。"),r("MIT 6.0001 Python Programming","https://ocw.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/","进阶","公开课","基础代数","用 Python 学习抽象、算法、测试和复杂度。"),r("Structure and Interpretation of Computer Programs","https://web.mit.edu/6.001/6.037/sicp.pdf","高级","开放教材","熟悉一种语言","从解释器、抽象和计算过程理解程序设计本质。")]),
 discrete:t("离散数学","学习逻辑、证明、图、组合与概率，为算法建立数学语言。",[r("Book of Proof","https://richardhammack.github.io/BookOfProof/","入门","开放教材","高中代数","从逻辑与集合进入严谨证明。"),r("MIT 6.042J Mathematics for Computer Science","https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-spring-2015/","进阶","公开课","编程与基础代数","覆盖证明、图论、计数、递推和离散概率。"),r("Mathematics for Computer Science","https://courses.csail.mit.edu/6.042/spring18/mcs.pdf","高级","开放教材","证明基础","MIT 完整开放教材，适合系统做题。")]),
 algorithms:t("数据结构与算法","研究如何正确、高效地组织数据并解决计算问题。",[r("Open Data Structures","https://opendatastructures.org/","入门","开放教材","一门编程语言","免费教材，以代码实现常见数据结构。"),r("MIT 6.006 Introduction to Algorithms","https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/","进阶","公开课","编程与离散数学","系统学习复杂度、数据结构、排序、图和动态规划。"),r("MIT 6.046J Design and Analysis of Algorithms","https://ocw.mit.edu/courses/6-046j-design-and-analysis-of-algorithms-spring-2015/","高级","公开课","算法基础与概率","进入随机、摊还、近似和高级图算法。")]),
 architecture:t("计算机组成","从逻辑门、指令和存储层次理解程序如何在硬件上运行。",[r("Nand2Tetris","https://www.nand2tetris.org/","入门","项目平台","基础编程","从 NAND 门逐步构建 CPU、汇编器、编译器和操作系统。"),r("MIT 6.004 Computation Structures","https://ocw.mit.edu/courses/6-004-computation-structures-spring-2017/","进阶","公开课","编程与离散数学","覆盖数字逻辑、处理器、存储与系统性能。"),r("Berkeley CS61C","https://cs61c.org/","高级","公开课","C、数据结构与数字逻辑","通过 RISC-V、缓存、并行和 C 深入机器结构。")]),
 systems:t("操作系统与系统编程","理解进程、虚拟内存、文件系统、并发和隔离。",[r("Operating Systems: Three Easy Pieces","https://pages.cs.wisc.edu/~remzi/OSTEP/","入门","开放教材","C 与计算机组成","免费教材，以虚拟化、并发和持久化组织操作系统。"),r("MIT 6.S081 Operating System Engineering","https://pdos.csail.mit.edu/6.S081/2021/","进阶","公开课","C、体系结构与调试","通过 xv6 实验实现系统调用、页表、文件系统和并发。"),r("MIT 6.033 Computer System Engineering","https://ocw.mit.edu/courses/6-033-computer-system-engineering-spring-2018/","高级","公开课","操作系统与网络基础","研究模块化、容错、性能、安全和分布式系统设计。")]),
 networks:t("计算机网络","理解分层、路由、可靠传输、拥塞控制和互联网协议。",[r("Computer Networking: Principles, Protocols and Practice","https://www.computer-networking.info/","入门","开放教材","编程基础","开放教材，从应用层到链路层理解互联网。"),r("Stanford CS144 Lecture Notes","https://www.scs.stanford.edu/10au-cs144/notes/","进阶","公开课","C++ 与系统编程","公开讲义覆盖可靠传输、TCP、路由、DNS、链路层和网络安全。"),r("MIT 6.829 Computer Networks","https://ocw.mit.edu/courses/6-829-computer-networks-fall-2002/","高级","公开课","概率、算法与系统","从论文和协议设计角度研究网络。")]),
 databases:t("数据库","学习关系模型、SQL、索引、事务和分布式数据系统。",[r("CMU 15-445 Database Systems","https://15445.courses.cs.cmu.edu/","入门","公开课","C++ 与数据结构","课程视频与数据库内核项目完整。"),r("Database Design — Open Textbook","https://opentextbc.ca/dbdesign01/","进阶","开放教材","SQL 基础","系统讲解关系建模、规范化、查询和事务。"),r("MIT 6.824 Distributed Systems","https://pdos.csail.mit.edu/6.824/","高级","公开课","系统、并发与网络","通过 Raft、KV 服务和分片实验理解分布式存储。")]),
 software:t("软件工程","把可运行代码发展为可测试、可维护、可协作的系统。",[r("The Missing Semester of Your CS Education","https://missing.csail.mit.edu/","入门","公开课","基础编程","补齐 Shell、Git、编辑器、调试和自动化。"),r("Software Engineering at Google","https://abseil.io/resources/swe-book","进阶","开放教材","项目经验","免费在线书，讨论规模、测试、依赖和团队协作。"),r("MIT 6.031 Software Construction","https://web.mit.edu/6.031/www/sp21/","高级","公开课","Java 与数据结构","围绕规格、测试、抽象、并发和代码审查构建可靠软件。")]),
 ai:t("人工智能与机器学习","理解搜索、概率、优化、表示学习与模型评估。",[r("MIT 6.034 Artificial Intelligence","https://ocw.mit.edu/courses/6-034-artificial-intelligence-fall-2010/","入门","公开课","Python、算法与线性代数","覆盖搜索、约束、学习、神经网络和推理。"),r("Stanford CS229 Machine Learning","https://cs229.stanford.edu/","进阶","公开课","概率、线性代数、微积分与编程","系统学习监督、无监督、生成模型和学习理论。"),r("Dive into Deep Learning","https://d2l.ai/","高级","开放教材","机器学习与 Python","带可运行代码的开放教材，深入现代深度学习。")]),
 security:t("计算机安全","学习威胁建模、密码学、软件漏洞和系统防御。",[r("Security Engineering — Ross Anderson","https://www.cl.cam.ac.uk/~rja14/book.html","入门","开放教材","系统与网络基础","作者免费提供的安全工程教材，从真实系统失败出发。"),r("MIT 6.858 Computer Systems Security","https://css.csail.mit.edu/6.858/2020/","进阶","公开课","操作系统、网络与 C","通过攻击和防御案例理解 Web、系统和隔离。"),r("Cryptopals Crypto Challenges","https://cryptopals.com/","高级","项目平台","编程、概率与基础密码学","用逐步挑战实现并攻击密码协议。")]),
 projects:t("项目与进阶方向","用可运行、可测试、可部署的作品形成能力。",[r("Build Your Own X","https://github.com/codecrafters-io/build-your-own-x","入门","项目平台","一门编程语言","通过重建数据库、Git、容器或解释器理解系统。"),r("Teach Yourself Computer Science","https://teachyourselfcs.com/","进阶","公开讲义","完成编程、算法和系统基础","按核心领域继续补齐体系结构、网络、数据库和分布式系统。"),r("Papers We Love","https://paperswelove.org/","高级","项目平台","成熟的系统与算法基础","阅读经典论文并复现核心算法或实验。")]),books:t("书单与资源","集中查看开放教材与大学课程。",[])
};
export const computerScience:SubjectConfig={slug:"computer-science",name:"计算机",en:"COMPUTER SCIENCE",intro:"计算机科学研究信息如何被表示、计算和可靠地组织。这条路径从编程进入算法、机器与系统，最终以真实项目形成能力。",caution:"不要只跟着视频复制代码。每个阶段都要离开教程，独立调试、测试、阅读文档并解释程序为什么正确。",groups:[...starts,["起点",[["tools","学习工具"],["programming","编程基础"],["discrete","离散数学"]]],["核心",[["algorithms","数据结构与算法"],["architecture","计算机组成"],["systems","操作系统与系统编程"],["networks","计算机网络"],["databases","数据库"]]],["构建与前沿",[["software","软件工程"],["ai","人工智能与机器学习"],["security","计算机安全"],["projects","项目与进阶方向"],["books","书单与资源"]]]],topics:csTopics,phases:[{time:"2–3 个月",title:"学会编程和调试",goal:"用一门语言独立表达问题。",learn:"变量、控制流、函数、数据结构、测试、命令行和 Git。",done:"不照教程完成一个命令行项目。",link:"programming"},{time:"3–5 个月",title:"建立算法与数学基础",goal:"理解正确性和效率。",learn:"证明、复杂度、排序、树、哈希、图和动态规划。",done:"能解释复杂度并独立实现核心数据结构。",link:"algorithms"},{time:"4–7 个月",title:"理解计算机系统",goal:"知道代码如何被机器和操作系统执行。",learn:"数字逻辑、CPU、内存、进程、并发和文件系统。",done:"完成体系结构或小型操作系统实验。",link:"systems"},{time:"3–5 个月",title:"连接网络与数据",goal:"理解真实服务如何通信和保存状态。",learn:"TCP/IP、HTTP、关系模型、索引、事务与分布式基础。",done:"构建带数据库和网络接口的服务。",link:"networks"},{time:"持续",title:"用工程项目深化方向",goal:"形成可维护、可复现的作品。",learn:"测试、文档、部署、安全，并选择 AI、系统、数据或理论方向。",done:"发布一个有说明、测试和版本历史的完整项目。",link:"projects"}],tools:[...commonTools,["开发环境",[["Visual Studio Code","https://code.visualstudio.com/","编辑、调试和管理代码"],["Git","https://git-scm.com/","版本控制与协作"],["Docker","https://www.docker.com/","创建可复现的运行环境"]]]],books:[["SICP","https://web.mit.edu/6.001/6.037/sicp.pdf","程序设计 · 进阶","通过抽象与解释器理解计算。"],["Open Data Structures","https://opendatastructures.org/","算法 · 入门","免费数据结构教材。"],["Operating Systems: Three Easy Pieces","https://pages.cs.wisc.edu/~remzi/OSTEP/","系统 · 进阶","免费操作系统经典教材。"],["Software Engineering at Google","https://abseil.io/resources/swe-book","工程 · 进阶","大规模软件工程实践。"]],portals:[["清华","清华大学：数据结构","https://v1-www.xuetangx.com/courses/course-v1%3ATsinghuaX%2B30240184%2Bsp/about","国家级精品课程，系统讲解数据结构设计、实现与算法分析。"],["北大","北京大学：人工智能与信息社会","https://www.icourse163.org/course/PKU-1003471009","面向初学者理解人工智能原理、应用与社会影响。"],["MIT","MIT OCW EECS","https://ocw.mit.edu/search/?d=Electrical%20Engineering%20and%20Computer%20Science","算法、AI、系统和理论课程。"],["Harvard","CS50 OpenCourseWare","https://cs50.harvard.edu/x/","高质量综合入门课程。"],["CMU","CMU Computer Science Courses","https://csd.cmu.edu/academics/all-courses","查找系统、数据库、AI 与理论课程。"],["Stanford","Stanford Engineering Everywhere","https://see.stanford.edu/Course","公开计算机与工程课程。"]]};
